equinor/dm-core-packages

- packages/yaml-view/package.json
- packages/yaml-view/tsconfig.json
fix build error with view-yaml package
error with using the view-yaml when installing from npm/yarn - just get an error saying yaml plugin crashed. (found when trying to use the package in analysis portal)
> fix: build view-yaml bug

- packages/dm-core/package.json
- packages/dm-core/src/hooks/useDocument.tsx
add correct type to document returned from useDocument
add type hinting for developer
part of #28
> fix: add type to document in useDocument

- .github/workflows/on-main-push.yaml
The `set-output` command in the GitHub Actions workflows, [is about to become deprecated](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/).
To change from the 
```sh
echo "::set-output name=tag-ref::TAG_REF"
```
to the new
```sh
echo "tag-ref=$TAG_REF" >> $GITHUB_OUTPUT
```
stanza
> Fix: replace deprecated output definition

- example/src/App.js
- packages/dm-core/package.json
- packages/dm-core/src/components/NewEntityButton.tsx
update NewEntityButton to manually add the name from user in the created entity.
The DMSS endpoint for instantiating an entity does not include a name in the returned entity.
> fix: handle entity name when using DMSS' instantiateEntity endpoint in newEntityButton

- .gitignore
- packages/dm-core/package.json
- packages/dm-core/src/components/UiPluginSelector.tsx
- packages/dm-core/src/components/UiRecipesSelector.tsx
- packages/dm-core/src/components/UiRecipesSideBarSelector.tsx
- packages/dm-core/src/context/UiPluginContext.tsx
- packages/dm-core/src/types.ts
- packages/tabs/src/TabsContainer.tsx
- Remove the "category" prop from "IUIPlugin"
-  Adds a config type for "UiPluginSelector" - allowing to specify a list of recipes to present for selection
- UiPluginSelector now has the common "IUIPlugin"-interface
- UiPluginContext
- Removed "getPagePlugin"
- Adds builtin plugins to list of loaded plugins
-  "getUiPlugin" now returns "() => JSX.Element" instead of an object
- Should be possible to use "Tabs" as an "initialRecipe"
needed for #55
> refactor(dm-core): update builtin plugins

- example/app/data/DemoDataSource/DemoPackage/BlueprintWithComplexChildren.json
- example/app/data/DemoDataSource/DemoPackage/TabsPluginConfig.json
- example/app/data/DemoDataSource/DemoPackage/UiPluginSelectorConfig.json
- example/app/data/DemoDataSource/DemoPackage/complexEntity.json
- example/app/data/DemoDataSource/DemoPackage/recipe_links/complex_blueprint.json
- example/package.json
- example/src/plugins.js
- packages/tabs/README.md
- packages/tabs/blueprints/TabsPluginConfig.json
- packages/tabs/package.json
- packages/tabs/src/TabsContainer.tsx
- Tabs plugin now uses the "UiRecipeSelector", allowing it to render "initialRecipes"
-  Adds a "TabsPluginConfig"-blueprint. Allow for configuring auto rendering of tabs and specifying plugin for 'home tab'
- Adds a complex test entity in the example project
- Should be possible to use "Tabs" as an "initialRecipe"
closes #56
> refactor: tabs 2.0

- packages/blueprint/package.json
- packages/default-pdf/package.json
- packages/default-preview/package.json
- packages/dm-core/package.json
- packages/explorer/package.json
- packages/form/README.md
- packages/form/package.json
- packages/header/package.json
- packages/job/package.json
- packages/mermaid/package.json
- packages/tabs/README.md
- packages/tabs/package.json
- packages/yaml-view/package.json
Standardizes the build scripts between packages
Ensures blueprints are uploaded to npm
> refactor: Standardize build scripts

- packages/explorer/package.json
- packages/explorer/src/Editor.tsx
- use UIRecipeSelector instead of UIPluginSelector
Explorer should render initialRecipes
closes #76
> fix(explorer): use initialRecipe renderer

- packages/dm-core/package.json
- packages/dm-core/src/domain/Tree.tsx
- Add the user provided name of the blueprint before saving it
The "Create blueprint" dialog asks to provide a name. So it should be put in the new blueprint entity.
closes #74
> fix(core): create blueprint with name

- example/app/data/DemoDataSource/DemoPackage/entities/tabsStandardEntity.json
- packages/dm-core-plugins/package.json
- packages/dm-core-plugins/src/tabs/Sidebar.tsx
- packages/dm-core-plugins/src/tabs/Tabs.tsx
- packages/dm-core-plugins/src/tabs/utils.ts
- "tabs" plugin label text now has fallback values if the entity does not have a "name"-attribute
see #101 
closes #101
> fix: tab label priority. label -> name -> attribute

- packages/dm-core/src/components/ViewCreator/ReferenceView.tsx
- packages/dm-core/src/hooks/useRecipe.tsx
* Find recipe only after loading is finished
* It will throw an error saying that the recipe is not found if it's try to find it to early
> fix: find recipe after loading finished

- example/app/data/DemoDataSource/DemoPackage/blueprints/Plugins/AttributeSelectorPluginConfig.json
- example/app/data/DemoDataSource/DemoPackage/recipe_links/attribute_selector_sidebar_blueprint.json
- example/app/data/DemoDataSource/DemoPackage/recipe_links/attribute_selector_tabs_blueprint.json
- packages/dm-core-plugins/blueprints/tabs/AttributeSelectorPluginConfig.json
- packages/dm-core-plugins/src/attribute-selector/AttributeSelectorPlugin.tsx
- packages/dm-core-plugins/src/attribute-selector/README.md
- packages/dm-core-plugins/src/attribute-selector/Sidebar.tsx
- packages/dm-core-plugins/src/attribute-selector/Tabs.tsx
add option to hide attributes in the attribute selector plugin.  This can be controlled by the config (see packages/dm-core-plugins/blueprints/tabs/AttributeSelectorPluginConfig.json)
closes #119
> feat: add option to hide attributes in attribute selector plugin

- packages/dm-core-plugins/src/attribute-selector/AttributeSelectorPlugin.tsx
- packages/dm-core-plugins/src/attribute-selector/Content.tsx
- packages/dm-core/package.json
- set CSS prop "fill-available" on some wrappers
- some plugins were being squashed
Before:
After:
closes #148
> fix: content of sidebar now fills available space

- packages/dm-core-plugins/package.json
- packages/dm-core-plugins/src/form/FormPlugin.tsx
- packages/dm-core-plugins/src/form/fields/ObjectField.tsx
- packages/dm-core/package.json
- packages/dm-core/src/components/UiPluginSelector.tsx
- packages/dm-core/src/components/UiRecipesSideBarSelector.tsx
- packages/dm-core/src/hooks/useBlueprint.tsx
- packages/dm-core/src/hooks/useRecipe.tsx
- packages/dm-core/src/utils/ErrorBoundary.tsx
- "form" will throw error on failed blueprint fetches
- update ErrorBoundary to display error and plugin name
- "form" would silently continue even if it failed to fetch a blueprint. Making it hard to detect errors/bad config
none
> fix(form): fix a bug where form continued with bad state

- example/app/data/DemoDataSource/DemoPackage/recipe_links/attribute_selector_sidebar_blueprint.json
- example/app/data/DemoDataSource/DemoPackage/recipe_links/attribute_selector_tabs_blueprint.json
- example/app/data/DemoDataSource/DemoPackage/recipe_links/dashboard.json
- example/app/data/DemoDataSource/DemoPackage/recipe_links/dummy_blueprint.json
- example/app/data/DemoDataSource/DemoPackage/recipe_links/example_application.json
- example/app/data/DemoDataSource/DemoPackage/recipe_links/formBlueprint.json
- example/app/data/DemoDataSource/DemoPackage/recipe_links/nested.json
- example/app/data/DemoDataSource/DemoPackage/recipe_links/singleField.json
- packages/dm-core-plugins/package.json
- packages/dm-core-plugins/src/index.tsx
rename dm core plugins -> append prefix `@development-framework/dm-core-plugins/`to all plugins
closes #96
> refactor: rename header plugin

- packages/dm-core-plugins/package.json
- packages/dm-core-plugins/src/header/HeaderPlugin.tsx
- packages/dm-core-plugins/src/header/README.md
allow no config for header plugin
closes #97
> fix: allow no config for header plugin

- packages/dm-core-plugins/package.json
- packages/dm-core-plugins/src/explorer/ExplorerPlugin.tsx
- packages/dm-core-plugins/src/explorer/style.css
make it possible to scroll in left and right side panels in the explorer plugin.
closes #128
> fix: make tree view and right window in explorer plugin scrollable

- packages/dm-core/package.json
- packages/dm-core/src/components/EntityView.tsx
- packages/dm-core/src/components/RecipeSelector.tsx
- packages/dm-core/src/components/ViewCreator/ViewCreator.tsx
- packages/dm-core/src/components/ViewCreator/utils.ts
- packages/dm-core/src/hooks/useDocument.test.tsx
- packages/dm-core/src/hooks/useDocument.tsx
- packages/dm-core/src/hooks/useRecipe.tsx
- packages/dm-core/src/types.ts
- Added option for "useRecipe" to not use "initialRecipes" (needed to avoid recursion on generated fall back ViewConfigs)
- Support for ViewConfigs with no recipe (needed for generated ViewConfigs based on attribute only)
- Partial support for special scope keyword 'self'
- A more standardized way of configuring plugins designed to accomodate multiple views 
needed for #151
> feature(ViewCreator): update to handle views with no recipe

- example/app/data/DemoDataSource/DemoPackage/entities/Dashboard/orderExample.json
- example/app/data/DemoDataSource/DemoPackage/recipe_links/order.json
- example/app/data/DemoDataSource/DemoPackage/recipe_links/orderItem.json
- example/src/App.js
- packages/dm-core-plugins/blueprints/generic-list/GenericListPluginConfig.json
- packages/dm-core-plugins/blueprints/generic-list/package.json
- packages/dm-core-plugins/src/generic-list/GenericListPlugin.tsx
- packages/dm-core-plugins/src/index.tsx
- packages/dm-core-plugins/src/yaml/YamlPlugin.tsx
- packages/dm-core/package.json
- packages/dm-core/src/components/EntityView.tsx
- packages/dm-core/src/components/ViewCreator/utils.ts
- packages/dm-core/src/context/UiPluginContext.tsx
- packages/dm-core/src/hooks/useRecipe.tsx
- packages/dm-core/src/types.ts
- Adds a new plugin "generic-list"
- Update "useRecipe" to select a recipe with a matching "dimensions"
- Framework should be able to render attributes of entities, even when they are lists
fixes parts of #109
> feature(generic-list): added generic list plugin

- .pre-commit-config.yaml
- example/package.json
- example/public/index.html
- packages/dm-core-plugins/src/blueprint/BlueprintPlugin.tsx
- packages/dm-core-plugins/src/form/fields/BooleanField.test.tsx
- packages/dm-core-plugins/src/form/fields/NumberField.test.tsx
- packages/dm-core-plugins/src/form/fields/ObjectField.test.tsx
- packages/dm-core-plugins/src/form/fields/StringField.test.tsx
- packages/dm-core-plugins/src/job/JobControlPlugin.tsx
- packages/dm-core-plugins/src/job/JobInputEditPlugin.tsx
- packages/dm-core-plugins/src/yaml/YamlPlugin.tsx
- packages/dm-core/src/domain/Tree.tsx
- packages/dm-core/src/hooks/useDocument.tsx
- packages/dm-core/src/hooks/useRecipe.tsx
Updates the pre-commit hooks and fixes code according to it suggestions. Also removes the eslint config from package.json, since we're only using eslint through the pre-commit and having them there caused some strange errors when building
> fix: avoid eslint failure

- packages/dm-core-plugins/package.json
- packages/dm-core-plugins/src/blueprint-hierarchy/BlueprintHierarchyPlugin.tsx
- packages/dm-core-plugins/src/blueprint-hierarchy/loader.tsx
- packages/dm-core-plugins/src/explorer/components/context-menu/ContextMenu.tsx
- packages/dm-core-plugins/src/form/Form.test.tsx
- packages/dm-core-plugins/src/form/fields/ArrayField.test.tsx
- packages/dm-core-plugins/src/form/fields/ArrayField.tsx
- packages/dm-core-plugins/src/form/fields/AttributeField.test.tsx
- packages/dm-core-plugins/src/form/fields/BooleanField.test.tsx
- packages/dm-core-plugins/src/form/fields/NumberField.test.tsx
- packages/dm-core-plugins/src/form/fields/ObjectField.test.tsx
- packages/dm-core-plugins/src/form/fields/ObjectField.tsx
- packages/dm-core-plugins/src/form/fields/StringField.test.tsx
- packages/dm-core-plugins/src/form/test-utils.tsx
- packages/dm-core-plugins/src/generic-list/GenericListPlugin.tsx
- packages/dm-core-plugins/src/generic-list/GenericTablePlugin.tsx
- packages/dm-core-plugins/src/header/components/UserInfoDialog.tsx
- packages/dm-core-plugins/src/job/JobControl.tsx
- packages/dm-core-plugins/src/pdf/PDFViewer.tsx
- packages/dm-core-plugins/src/react-notifications.d.ts
- Use dmss context in dm-core-plugins
- add react-notifications types to avoid ts errors (note that the typings are more or less copy pasted from https://github.com/minhtranite/react-notifications/issues/29#issuecomment-648846225 and I have not verified that it's 100% correct)
Refs #174
> refactor: use dmss context

- example/app/data/DemoDataSource/DemoPackage/blueprints/Product.json
- packages/dm-core-plugins/package.json
- packages/dm-core-plugins/src/form/Form.tsx
- packages/dm-core-plugins/src/form/fields/NumberField.test.tsx
- packages/dm-core-plugins/src/form/fields/NumberField.tsx
- packages/dm-core-plugins/src/form/fields/StringField.test.tsx
- packages/dm-core-plugins/src/form/fields/StringField.tsx
- packages/dm-core-plugins/src/form/widgets/TextWidget/TextWidget.tsx
- packages/dm-core-plugins/src/form/widgets/TextareaWidget/TextareaWidget.tsx
fix bug in form:
bug:
1) update an optional text field (for example `aOptionalNumber` in FormExample.json)
2) save
3) update the same text field:  delete the content of `aOptionalNumber` textfield
4) save
After these steps, the document in the database has an empty string stored in the `aOptionalNumber` attribute. 
There are 2 things wrong with this:
1) even though type is a number, the saved value is a string
2) the attribute should not even be saved in the document
The correct behavior is to remove the attribute from the document.
closes #146
> fix: bug when saving optional value in form plugin

- example/app/data/DemoDataSource/DemoPackage/recipe_links/order.json
- example/app/data/DemoDataSource/DemoPackage/recipe_links/orderItem.json
- example/src/App.js
- packages/dm-core-plugins/src/attribute-selector/AttributeSelectorPlugin.tsx
- packages/dm-core-plugins/src/attribute-selector/Content.tsx
- packages/dm-core-plugins/src/attribute-selector/Sidebar.tsx
- packages/dm-core-plugins/src/attribute-selector/Tabs.tsx
- packages/dm-core-plugins/src/attribute-selector/types.tsx
- packages/dm-core-plugins/src/blueprint/BlueprintPlugin.tsx
- packages/dm-core-plugins/src/form/Form.tsx
- packages/dm-core-plugins/src/form/FormPlugin.tsx
- packages/dm-core-plugins/src/form/RegistryContext.tsx
- packages/dm-core-plugins/src/form/components/OpenObjectButton.tsx
- packages/dm-core-plugins/src/form/fields/ArrayField.tsx
- packages/dm-core-plugins/src/form/fields/ObjectField.tsx
- packages/dm-core-plugins/src/form/types.tsx
- packages/dm-core-plugins/src/generic-list/GenericListPlugin.tsx
- packages/dm-core-plugins/src/generic-list/GenericTablePlugin.tsx
- packages/dm-core-plugins/src/grid/GridElement.tsx
- packages/dm-core-plugins/src/job/JobControlPlugin.tsx
- Update "attribute-selector" plugin to pass "onOpen" to Views
- Update "form"-plugins ArrayField to not render lists of complex lists if "onOpen" is passed
- Changes to "view-concept" and "attribute-selector" caused "onOpen" to no longer function
closes #127
> fix(attribute-selector): pass "onOpen" to views

- example/reset-all.sh
- packages/dm-core-plugins/package.json
- packages/dm-core-plugins/src/attribute-selector/AttributeSelectorPlugin.tsx
- packages/dm-core-plugins/src/attribute-selector/Content.tsx
- packages/dm-core-plugins/src/generic-list/GenericListPlugin.tsx
- packages/dm-core/package.json
- packages/dm-core/src/components/EntityView.tsx
- packages/dm-core/src/components/RecipeSelector.tsx
- packages/dm-core/src/components/ViewCreator/ViewCreator.tsx
- packages/dm-core/src/components/ViewCreator/utils.ts
- packages/dm-core/src/domain/types.ts
- packages/dm-core/src/hooks/useRecipe.tsx
- packages/dm-core/src/utils/ErrorBoundary.tsx
- Fix a bug in the viewcreator where type and dimensions(missing) where assumed found in entity, instead of blueprints
- "<EntityView>" needs to know if the target is a list or not, and of what type
hotfix
> fix(ViewCreator): get type and dimensions from blueprints

- packages/dm-core-plugins/package.json
- packages/dm-core-plugins/src/attribute-selector/Content.tsx
- packages/dm-core-plugins/src/generic-list/GenericListPlugin.tsx
- packages/dm-core-plugins/src/grid/GridElement.tsx
- packages/dm-core-plugins/src/grid/GridItems.tsx
- packages/dm-core-plugins/src/grid/GridPlugin.tsx
- packages/dm-core/package.json
- packages/dm-core/src/components/EntityView.tsx
- packages/dm-core/src/components/RecipeSelector.tsx
- packages/dm-core/src/components/ViewCreator/ViewCreator.tsx
- packages/dm-core/src/hooks/useRecipe.tsx
- ViewCreator needs to know the type for the root entity, in order to find the type for the scope
- Updated Grid plugin to pass root entity type to ViewCreator
none
> fix(grid): pass type to grid elements

- packages/dm-core-plugins/src/form/fields/ObjectField.tsx
* Fix a bug in form in onOpen scope, that should not always include attributePath
> fix: attribute path should not be included all times

- packages/dm-core/src/components/ViewCreator/utils.ts
* The getScopeTypeAndDimensions should handle scope with more than 1 level
> fix: handle scope with more than 1 level

- .github/workflows/tests.yaml
Use the local dm-core variant when testing packages
When updating dm-core, we had to first merge the changes to dm-core in on PR to get a new npm release, before updating dm-core-plugins to use the newest functionality in another PR due to issues in testing.
Closes #389
> ci: test dm-core-plugins with newest dm-core

- packages/dm-core-plugins/src/form/fields/ArrayField.tsx
- packages/dm-core-plugins/src/form/fields/ObjectField.tsx
- packages/dm-core/src/domain/Tree.tsx
- packages/dm-core/src/hooks/useDocument.test.tsx
- packages/dm-core/src/hooks/useDocument.tsx
- packages/dm-core/src/hooks/useJob.tsx
- packages/dm-core/src/services/api/configs/gen/api/default-api.ts
- packages/dm-core/src/services/api/configs/gen/api/document-api.ts
- packages/dm-core/src/services/api/configs/gen/models/entity.ts
- packages/dm-core/src/services/api/configs/gen/models/recipe.ts
- packages/dm-core/src/services/api/configs/gen/models/reference.ts
- packages/dm-core/src/utils/test-utils-dm-core.tsx
* Update to use the document get endpoint instead of get-by-path and get-by-id endpoint
Related to https://github.com/equinor/data-modelling-storage-service/pull/421
> refactor: use get document endpoint

- example/app/data/DemoDataSource/apps/MySignalApp/instances/CaseUISelector.json
- example/app/data/DemoDataSource/apps/MySignalApp/package.json
- example/app/data/DemoDataSource/recipes/apps/signal_app/recipe_links/appDefault.json
- example/app/data/DemoDataSource/recipes/apps/signal_app/recipe_links/containers/EquallySpacedSignalUI.json
- example/app/data/DemoDataSource/recipes/apps/signal_app/recipe_links/signalAppUI.json
- example/app/data/DemoDataSource/recipes/apps/signal_app/recipe_links/signals_simple/CaseUI.json
- example/app/data/DemoDataSource/recipes/apps/signal_app/recipe_links/signals_simple/StudyNCUI.json
- example/app/data/DemoDataSource/recipes/package.json
- packages/dm-core/src/domain/Tree.tsx
- packages/dm-core/src/services/api/configs/gen/api/default-api.ts
- packages/dm-core/src/services/api/configs/gen/api/document-api.ts
- Fix some outdated names for types and plugins in the signalApp
- Update the DMSS TS API
- Fix Tree.ts to fetch enough depth to get name of TreeNodes
- Make the test app "SignalApp" work
none
> chore: bump DMSS version and update signalApp to match renamed blueprints

- example/docker-compose.yaml
- example/job_handlers/signal-app/__init__.py
- example/src/plugins/job-ui-single/pages/JobRunner.tsx
* Add job handler for signal app that does just add some values to the signal.value array so that it's possible to draw a graph. 
Note that the JobRunner.tsx and the Python job handler should be made better.
> refactor: add signal app job handler

- example/craco.config.js
- example/src/App.tsx
- packages/dm-core/package.json
- packages/dm-core/src/styles/main.css
Adds and a global css file to dm-core that users can import in their projects to handle stuff like reset margins, box-sizing and using Equinor font.
Less code for user.
> feat: export global css file for use in external projects

- .github/workflows/remove-integration-tests-report.yaml
* Missing to specify type for an input
> ci: missing type of input

- packages/dm-core-plugins/blueprints/grid/GridSize.json
- packages/dm-core-plugins/src/grid/GridPlugin.tsx
- packages/dm-core-plugins/src/grid/types.ts
- Add rowGap and columnGap attributes to GridSize blueprint
- Set rowGap and columnGap + default in Grid plugin component
- Let's user configure gap between elements in Grid component + sets a more common default size (16px)
> feat: add support for grid gap config

- packages/dm-core-plugins/package.json
- packages/dm-core-plugins/src/attribute-selector/AttributeSelectorPlugin.tsx
- packages/dm-core-plugins/src/attribute-selector/Tabs.tsx
- packages/dm-core-plugins/src/attribute-selector/styles.ts
- packages/dm-core-plugins/src/attribute-selector/types.tsx
- Switch tabs from custom styling to EDS
- Allow tabs that have been opened/added to view to be closed again
- Remove non-uniform styling
- Request from Babak to be able to close views after opening them
> feat: make tabs closeable + eds switch

- packages/dm-core-plugins/src/form/fields/ObjectField.test.tsx
Unskip ObjectField tests and fix a small bug.
It should never have been skiped. https://github.com/equinor/dm-core-packages/pull/178#discussion_r1168348050
> test: unskip objectfield testing

- packages/dm-core-plugins/src/form/fields/ObjectField.test.tsx
- Stop using the describe syntax in tests (it is more verbose and less robust)
- Avoid using container (we should query on things the user can see, ie labels etc, not ids and types)
- Rewrite some of the tests
> refactor: objectfield test

- packages/dm-core-plugins/src/attribute-selector/AttributeSelectorPlugin.tsx
When closing a tab (view), instead just selecting "self": select next tab if it exists, select previous tab if it doesn't, select self if the previous two aren't an option. This seems to be the default in browsers.
Feels unnatural that it always goes to self.
> feat: select next, previous then self on view/tab close

- .github/workflows/on-main-push.yaml
Try to publish packages using root folder and yarn workspaces
Run currently fails because dm-core-plugins can't locate dm-core after removing linking of packages
> fix: publish packages using root folder

- e2e/tests/plugin-form-Simple.spec.ts
- example/app/data/DemoDataSource/plugins/form/simple/blueprints/Simple.json
- example/app/data/DemoDataSource/plugins/form/simple/simple.json
Expanded the simple form plugin to include all types of primitives, with some variations.
The e2e-test have been updated. Note that some lines have been commented out because there is a bug in the form package which will cause the test to fail and we don´t want this test to stop other work for now. See [https://github.com/orgs/equinor/projects/189?pane=issue&itemId=31708452](https://github.com/orgs/equinor/projects/189?pane=issue&itemId=31708452 )
> fix: expanded simple-form pluging and updated e2e

- packages/dm-core-plugins/blueprints/attribute-selector/AttributeSelectorItem.json
- packages/dm-core-plugins/src/attribute-selector/Content.tsx
- packages/dm-core-plugins/src/attribute-selector/README.md
- packages/dm-core-plugins/src/form/fields/ObjectField.tsx
- packages/dm-core/src/components/ViewCreator/ViewCreator.tsx
add error handling to attribute selector plugin. 
Do not crash if a single attribute is not found
requires https://github.com/equinor/data-modelling-storage-service/pull/456
#220
> fix: better error handing in attriubte selector

- packages/dm-core-plugins/src/form/Form.tsx
- packages/dm-core-plugins/src/form/FormPlugin.tsx
- packages/dm-core-plugins/src/form/RegistryContext.tsx
- packages/dm-core-plugins/src/form/components/OpenObjectButton.tsx
- packages/dm-core-plugins/src/form/context/WidgetContext.tsx
- packages/dm-core-plugins/src/form/fields/BooleanField.tsx
- packages/dm-core-plugins/src/form/fields/NumberField.tsx
- packages/dm-core-plugins/src/form/fields/ObjectField.tsx
- packages/dm-core-plugins/src/form/fields/StringField.tsx
- packages/dm-core-plugins/src/form/types.tsx
- packages/dm-core-plugins/src/form/widgets/BlueprintPickerWidget.tsx
- packages/dm-core-plugins/src/form/widgets/CheckboxWidget.tsx
- packages/dm-core-plugins/src/form/widgets/CheckboxWidget/index.ts
- packages/dm-core-plugins/src/form/widgets/TextWidget.tsx
- packages/dm-core-plugins/src/form/widgets/TextWidget/index.ts
- packages/dm-core-plugins/src/form/widgets/TextareaWidget.tsx
- packages/dm-core-plugins/src/form/widgets/TextareaWidget/index.ts
- packages/dm-core-plugins/src/form/widgets/TypeWidget.tsx
- packages/dm-core-plugins/src/form/widgets/Widgets.ts
- packages/dm-core-plugins/src/form/widgets/index.ts
- packages/dm-core-plugins/src/form/widgets/index.tsx
I've removed some unnecessary folder levels and index files from form/widgets
I've moved two widgets that were defined in <Form/> into separate files
I've created a widget context and removed widget logic from the registrycontext. The widget context can be wrapped around an application to allow for custom widgets
Refs #266
> feat: enable custom form widgets

- packages/dm-core-plugins/src/generic-list/GenericTablePlugin.tsx
fix bug: before, when opening an unsaved row we got this error
the bug is now fixed - user have to press save before opening a case
#220
> fix: bug when opening unsaved table row

- example/app/data/DemoDataSource/recipes/plugins/generic-list/orderItem.json
- example/app/data/DemoDataSource/recipes/plugins/grid/orderItem.json
- packages/dm-core-plugins/src/generic-list/GenericListPlugin.tsx
- packages/dm-core-plugins/src/table/TablePlugin.tsx
- packages/dm-core-plugins/src/table/types.ts
fix some issues with the generic list plugin and the generic list example:
- the recipe for orderitem was wrong. Before, we tried to use the generic list plugin on a document that was NOT a list (the generic list plugin was used on an entity of type OrderItem)
-  update generic list plugin to have similar behaviour as the generic table plugin: do not call dmss when adding a row (instead, only call dmss when pressing save) and also add the `isSaved` attribute to ItemRow type
#220
> fix: bugs in generic list plugin

- release-please-config.json
* Could not start at 0.1.0, since npm does not allow us to delete old packages, changing to start at 1.1.0
> ci: change inital versions to start at 1.1.0

- example/README.md
- package.json
This pull request adds a step-by-step setup guide for Windows users to start the DMT Example application. 
It is a list of commands. 
It is tested that these steps works on a Windows computer. 
🪟 vs 🍎
The startup steps are not the same as for mac, and therefore the current step-by-steps did not work. Some people will need to access the application from Windows computers in the future, and therefore this guide is required. 
Not connected to an issue.
> 🪟 Docs/Readme for Windows Setup🪟

- .prettierignore
release-please autogenerate the content of the manifest file in a way that prettier does not like.
> chore: make prettier ignore manifest

- packages/dm-core-plugins/src/table/TablePlugin.tsx
- packages/dm-core-plugins/src/table/TableRow/TableRow.tsx
- packages/dm-core-plugins/src/table/types.ts
Quick refactor that puts table row as its own component to decrease the size and categorize functionality of TablePlugin
TablePlugin component was a bit large
> refactor: extract table row to own component

- .github/workflows/create-release-pr.yaml
* The output variable from release-please had a different name than publish-packages expected (spelling error)
> ci: correct output variable name from release please

- .github/workflows/on-main-push.yaml
- .github/workflows/publish-integration-tests-report.yaml
Fix two bugs in on-main-push
Ensure readme is only updated with the integration test result if it's triggered by push to main and the test is successful
Don't want to spam the readme
Refs #319
> ci: avoid publish test report

- example/app/data/DemoDataSource/plugins/view_selector/blueprints/AttributeSelectorSidebar.blueprint.json
- example/app/data/DemoDataSource/plugins/view_selector/blueprints/AttributeSelectorTabsDefault.blueprint.json
* Remove attribute type, since it already defined in named entity
> refactor: remove type since it is already defined in named entity

- packages/dm-core-plugins/src/form/fields/ObjectField.tsx
- packages/dm-core-plugins/src/form/types.tsx
Removes the <External /> component, as it is basically just an empty wrapper for EntityView
Refs #276
> refactor: remove external component from form

- packages/dm-core-plugins/blueprints/form/fields/ArrayField.json
- packages/dm-core-plugins/blueprints/form/fields/ObjectField.json
- packages/dm-core-plugins/src/form/types.tsx
I did a mistake earlier. The string referres to which of the attribute´s recipes should be shown, so "uiRecipe" makes more sense
> fix: rename plugin to uiRecipe in widget types

- example/app/data/DemoDataSource/recipes/apps/signal_app/recipe_links/signals_simple/case.recipe.json
- packages/dm-core-plugins/blueprints/table/TablePluginConfig.json
- packages/dm-core-plugins/src/table/TablePlugin.tsx
- packages/dm-core-plugins/src/table/TableRow/TableRow.tsx
- packages/dm-core-plugins/src/table/types.ts
- adds expandableRecipeViewConfig to table blueprint
- adds example expandableRecipeViewConfig to case recipe in signal app
- separate openAsTab and openAsExpandable in tableplugin so you can use both at the same time
Want to be able to add custom view in expandable that may differ from view in open/openAsTab
#258
> feat: ability to add custom viewrecipe in table expandable row

- example/docker-compose.yaml
When running "docker compose up" we were receiving two error messages related to image platform:
`! job-api The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested 0.0s`
` ! dmss The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested    0.0s` 
This PR adds `platform: linux/amd64` to the docker-compose file which removes these errors.
> fix: image platform error

- example/src/plugins/job-ui-single/pages/CreateJobEntity.tsx
- packages/dm-core-plugins/src/form/fields/ObjectField.tsx
- packages/dm-core/src/utils/addressUtilities.test.ts
- packages/dm-core/src/utils/addressUtilities.ts
Adds general utils for splitting an address into its parts and for resolving a relative address into an absolute address
Uses this utils to solve a bug in form. The bug caused issues with opening uncontained references with relative paths
Refs #276
> fix: relative reference bug in form

- e2e/tests/plugin-form-Nested.spec.ts
- example/app/data/DemoDataSource/plugins/form/nested/blueprints/Car.blueprint.json
- example/app/data/DemoDataSource/plugins/form/nested/myCarRentalCompany.entity.json
- example/app/data/DemoDataSource/recipes/plugins/form/nested/car.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/form/nested/customer.recipe.json
Added e2e-test for nested form example.
Added recipe for car and customer.
Some minor changes to blueprint and entity.
There is a known bug when saving the form, which causes an item to be saved twice when creating/editing. Some lines of the e2e-test have therefore been commented out.
> test: e2e for nested form

- example/app/data/DemoDataSource/recipes/apps/signal_app/recipe_links/signals_simple/case.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/form/nested/carRentalCompany.recipe.json
- packages/dm-core-plugins/blueprints/form/FormInput.json
- packages/dm-core-plugins/src/form/Form.test.tsx
- packages/dm-core-plugins/src/form/FormPlugin.tsx
- packages/dm-core-plugins/src/form/README.md
- packages/dm-core-plugins/src/form/fields/ObjectField.test.tsx
- packages/dm-core-plugins/src/form/fields/ObjectField.tsx
- packages/dm-core-plugins/src/form/types.tsx
Replace the order config with a fields config, that can be used both to order and to filter the form fields. If no config.fields is given, all fields are shown in the order of the blueprint
Blueprints often has a lot of meta info that does not need to be presented in a form. Being able to filter the attributes is important
Refs #276
> feat: allow form field filtering

- e2e/tests/plugin-table-car_list.spec.ts
- example/app/data/DemoDataSource/plugins/table/car_list/blueprints/Car.blueprint.json
- example/app/data/DemoDataSource/plugins/table/car_list/carList.entity.json
- example/app/data/DemoDataSource/recipes/plugins/table/car_list/carList.recipe.json
Added e2e-test for the table-plugin.
Some bugs noted in #258. Parts of the e2e-test is therefore temporarily commented out to avoid running into these bugs.
#153 is currently forcing us to reload the page in order view saved items.
> test: e2e for table plugin

- e2e/tests/plugin-form-Nested.spec.ts
- packages/dm-core-plugins/src/list/ListPlugin.tsx
Added title to the expand and minimize button for list plugin.
Updated e2e-test to utilise changes.
Makes it much easier and prettier when writing e2e-tests where the expand/minimise button is used.
Expand-button is also used when opening in a new tab from list plugin. The changes also apply in this case, as shown in the updated e2e-test.
> fix: added title to expand-minimize button

- packages/dm-core-plugins/src/list/Components.tsx
Added correct titles to each of the list item buttons.
The "up", "down" and "delete" buttons had the same title ("Move up").
> fix: add correct titles to list item buttons

- packages/dm-core-plugins/src/table/types.ts
The configs were made superfluous when expandableRecipeViewConfig were created, and were decided removed in https://github.com/equinor/dm-core-packages/pull/321#discussion_r1247788461
> refactor: remove unused views and defaultViews config

- packages/dm-core-plugins/src/form/fields/BooleanField.tsx
- packages/dm-core-plugins/src/form/fields/NumberField.tsx
- packages/dm-core-plugins/src/form/fields/ObjectField.tsx
- packages/dm-core-plugins/src/form/fields/StringField.tsx
Removes the control argument to avoid unnecessary noise
control input is optional when using form provider, which we do
#276
> refactor(form): remove superfluous control argument

- e2e/tests/plugin-form-Nested.spec.ts
- packages/dm-core-plugins/src/form/fields/ObjectField.tsx
Ensure the remove button is visible both for inline object form and in tab
You should always be able to remove an optional attribute. 
#276
> fix(form): show remove button

- packages/dm-core-plugins/src/form/fields/BooleanField.tsx
- packages/dm-core-plugins/src/form/fields/NumberField.tsx
- packages/dm-core-plugins/src/form/fields/StringField.tsx
- packages/dm-core-plugins/src/form/types.tsx
Avoid using type "any" for uiAttribute
#276
> refactor(form): give uiAttribute correct type

- .github/workflows/integration-tests.yaml
- example/README.md
- example/reset-all.sh
add validation as default in the reset all script. Validation can be turned off by adding the flag --no-validate-entities
NB!
after this is merged, you must run dm-cli v 1.0.16 or higher
https://github.com/equinor/dm-cli/issues/103
> fix: update reset script to work with dm-cli validation flag

- packages/dm-core-plugins/src/form/test-utils.tsx
- packages/dm-core/src/hooks/useRecipe.tsx
default uiRecipes are usually returned from the dmss. Unit tests don't have dmss, so we must mock this, or else it can fail.
#276
> test(form): mock uirecipes

- packages/dm-core-plugins/src/header/HeaderPlugin.tsx
- packages/dm-core/src/components/ViewCreator/InlineRecipeView.tsx
- packages/dm-core/src/context/UiPluginContext.tsx
- packages/dm-core/src/hooks/useRecipe.tsx
The UiPluginContext was made so that if the UiPluginProvider was missing, the UiPluginContext would simply return meaningless data. I've rewritten it to make sure it will fail properly.
> fix: raise warning on missing UiPluginProvider

- packages/dm-core/src/domain/Tree.tsx
do not display primitive attributes as sub nodes in the tree. see issue for more details
closes #395
> fix: do not add primitive types as separate nodes in tree

- e2e/tests/plugin-form-Nested.spec.ts
- packages/dm-core-plugins/src/form/fields/ObjectField.tsx
Made pressing the Remove button cause db to be updated. Also fixed button names to make this more obvious to the user
Pressing add caused db to be updated, but that was not the case for remove
#276
> fix(form): update db when pressing Remove button

- packages/dm-core/src/components/Pickers/EntityPickerButton.tsx
If the caller of EntityPickerButton want padding, they can add it themselves
> style(EntityPicker): remove button styling

- example/app/data/DemoDataSource/recipes/plugins/form/nested/carRentalCompany.recipe.json
- packages/dm-core-plugins/src/form/components/OpenObjectButton.tsx
- packages/dm-core-plugins/src/form/context/RegistryContext.tsx
- packages/dm-core-plugins/src/form/fields/ArrayField.test.tsx
- packages/dm-core-plugins/src/form/fields/ArrayField.tsx
- packages/dm-core-plugins/src/form/fields/ObjectField.tsx
- packages/dm-core-plugins/src/form/types.tsx
- packages/dm-core-plugins/src/table/types.ts
- packages/dm-core-plugins/src/view_selector/Content.tsx
- packages/dm-core-plugins/src/view_selector/ViewSelectorPlugin.tsx
- packages/dm-core/src/types.ts
- Refactor type of onOpen function to TOnOpen
- Update Form Open button to using recipe to select view
- Add example
Having a TOnOpen makes it less likely that we have different varieties of the type lying around
#276
> feat(form): use recipe on open

- packages/dm-core-plugins/jest.config.js
- packages/dm-core/jest.config.js
Removes the name config, since it doesn't exists, and only serves to give us validation warnings
> test(jest): remove validation warning

- example/docker-compose.yaml
> fix: stable job version

- example/app/data/DemoDataSource/plugins/form/simple/blueprints/Simple.blueprint.json
- example/app/data/DemoDataSource/plugins/form/simple/simple.entity.json
I found a bug in the number field that would have been found earlier had we had a proper example of the input field for mandatory numbers
> test(form): add required number field to example

- e2e/tests/plugin-form-Simple.spec.ts
- packages/dm-core-plugins/src/form/fields/NumberField.tsx
- packages/dm-core-plugins/src/form/fields/StringField.tsx
Make helpertext show and improve message
A helpertext should show up if you try to submit a form with an empty, mandatory number. Currently, it only got a red border.
> fix(form): numberfield doesn't display helpertext on missing, required number

- packages/dm-core-plugins/src/form/fields/NumberField.test.tsx
Complete rewrite of the numberfield tests.
The previous tests were testing a lot of things that were not relevant for the number field it was supposed to test.
> test(form): redefine number field tests

- packages/dm-core-plugins/src/file/FilePlugin.tsx
Removes an unused import
eslint is failing because of an unused import
> ci: fix eslint error

- example/app/data/DemoDataSource/plugins/form/storage_uncontained/blueprints/Result.blueprint.json
- example/app/data/DemoDataSource/plugins/form/storage_uncontained/blueprints/Simulation.blueprint.json
- example/app/data/DemoDataSource/plugins/form/storage_uncontained/result.entity.json
- example/app/data/DemoDataSource/plugins/form/storage_uncontained/simulation.entity.json
- example/app/data/DemoDataSource/recipes/plugins/form/storage_uncontained/result.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/form/storage_uncontained/simulation.recipe.json
Adds simple example
Need to make an example to work with when adapting form to storage uncontained.
> test(form): add example of storage uncontained

- example/app/data/DemoDataSource/plugins/form/nested/blueprints/CarRentalCompany.blueprint.json
- packages/dm-core-plugins/src/form/fields/AttributeField.tsx
- packages/dm-core-plugins/src/form/fields/ObjectField.tsx
- packages/dm-core-plugins/src/form/types.tsx
If a complex attribute (Object) has not been instantiated, but has a default value defined, the default value should be used upon creation. 
The instantiateEntity endpoint is currently used if we want to add a complex attribute, but it should instead first check if a default value is available in the blueprint.
Closes #470
> fix(form): ObjectField use default value if defined

- example/app/data/DemoDataSource/recipes/plugins/form/read_only/carRentalCompany.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/form/read_only/customer.recipe.json
- packages/dm-core-plugins/blueprints/form/FormInput.json
- packages/dm-core-plugins/src/form/components/AttributeList.tsx
- packages/dm-core-plugins/src/form/components/Form.tsx
- packages/dm-core-plugins/src/form/fields/ArrayField.tsx
- packages/dm-core-plugins/src/form/fields/AttributeField.tsx
- packages/dm-core-plugins/src/form/fields/ObjectField.tsx
- packages/dm-core-plugins/src/form/types.tsx
Removes the [Add and Save], [Select and Save], [Add], [Remove] and [Add Item] (ListPlugin) buttons when in read only mode.
It should not be possible to delete or add objects when in read only mode.
Closes #496
> fix: remove all edit buttons when in readOnly mode

- e2e/tests/plugin-form-ReadOnlyPrimitives.spec.ts
- example/app/data/DemoDataSource/plugins/form/read_only_primitives/blueprints/ReadOnlyPrimitives.blueprint.json
- example/app/data/DemoDataSource/plugins/form/read_only_primitives/readOnlyPrimitives.entity.json
- example/app/data/DemoDataSource/recipes/plugins/form/read_only_primitives/readOnlyPrimitives.recipe.json
Example and test for a readonly form
> test: readonly primitives

- e2e/tests/plugin-form-Nested.spec.ts
- e2e/tests/plugin-form-UncontainedObject.spec.ts
- e2e/tests/plugin-view_selector-car_garage.spec.ts
- packages/dm-core-plugins/src/common/TooltipButton.tsx
- packages/dm-core-plugins/src/form/components/OpenObjectButton.tsx
- packages/dm-core-plugins/src/form/fields/ArrayField.tsx
- packages/dm-core-plugins/src/form/fields/ObjectField.test.tsx
- packages/dm-core-plugins/src/form/fields/ObjectField.tsx
- packages/dm-core-plugins/src/form/styles.tsx
Form uses icon buttons with tooltip for opening, adding, editing and removing nested objects and list.
Also created a generic TooltipButton and adapted tests to the new layout
ref #488
> fix(form): use icons for form buttons

- packages/dm-core-plugins/package.json
- packages/dm-core-plugins/src/yaml/YamlPlugin.tsx
[js-yaml](https://www.npmjs.com/package/js-yaml) hasn't had a release in two years. Meanwhile, [yaml](https://www.npmjs.com/package/yaml) has TS support, recent release and, while not as popular as js-yaml, is still quite popular.
> chore: replace js-yaml with yaml

- packages/dm-core-plugins/src/explorer/ExplorerPlugin.tsx
- packages/dm-core-plugins/src/explorer/components/context-menu/ContextMenu.tsx
- packages/dm-core-plugins/src/explorer/components/context-menu/NodeRightClickMenu.tsx
- packages/dm-core-plugins/src/explorer/components/context-menu/utils/contextMenuActions.ts
- packages/dm-core-plugins/src/explorer/components/dialogs/AppendEntityDialog.tsx
- packages/dm-core-plugins/src/explorer/components/dialogs/DeleteDialog.tsx
- packages/dm-core-plugins/src/explorer/components/dialogs/NewBlueprintDialog.tsx
- packages/dm-core-plugins/src/explorer/components/dialogs/NewEntityDialog.tsx
- packages/dm-core-plugins/src/explorer/components/dialogs/NewFolderDialog.tsx
- packages/dm-core-plugins/src/explorer/components/dialogs/NewRootPackageDialog.tsx
The ContextMenu file was long and hard to get a grasp of, so I split it into multiple files. Also noticed that we were rendering 6 dialogs for each node in the tree, which seems a bit excessive, so I added an inline if around each render
> refactor(explorer): extract dialogs

- packages/dm-core/src/components/Pickers/DestinationPicker.tsx
- packages/dm-core/src/components/TreeView.tsx
Moves the SelectPackageButton so that it doesn't have to get the onSelect prop through the TreeView. Then remove the now unused NodeWrapperOnClick prop from TreeView
The onSelect function was passed into the TreeView and directly out again to the caller. It was only used in the DestinationPicker
> refactor(tree): remove onselect from wrapper props

- e2e/tests/plugin-view_selector-car_garage.spec.ts
- packages/dm-core-plugins/src/view_selector/Sidebar.tsx
Added "tab" as a role to the sidebar. When used this makes the playwright tests more readable.
Some other improvements to the test.
Chose to use "tab" as a role as that felt as the best fit.
> test: improve view-selector test

- e2e/tests/plugin-view_selector-car_garage.spec.ts
Temporary fix that hopefully solves the view selector playwright test from failing.
It looks like a previous tooltip gets in the way when clicking the collapse button. Added an extra click to get the tooltip away.
Closes #527
> fix: temp fix for view-selector test

- e2e/tests/plugin-form-Nested.spec.ts
- e2e/tests/plugin-form-ReadOnlyPrimitives.spec.ts
- e2e/tests/plugin-form-Simple.spec.ts
- e2e/tests/plugin-form-UncontainedObject.spec.ts
- e2e/tests/plugin-list-task_list.spec.ts
- e2e/tests/plugin-table-car_list.spec.ts
- e2e/tests/plugin-view_selector-car_garage.spec.ts
- e2e/tests/signalApp.spec.ts
- packages/dm-core/src/components/Pickers/EntityPickerDialog.tsx
- packages/dm-core/src/components/TreeView.tsx
- packages/dm-core/src/domain/Tree.tsx
Before, the tree used divs upon divs. But actually, a nested list with buttons is a more correct approach, so I fixed that. I've also kept further improvements in mind while working with this, so I hope I easily can add new functionality on top of this.
Makes it easier to navigate in tests and increases accessibility. Hopefully, the code is easier to maintain too.
ref #534
> refactor(tree): switch html structure from div to ul

- e2e/tests/plugin-form-UncontainedObject.spec.ts
- e2e/tests/signalApp.spec.ts
I added title to the svg icons, causing some of the tree selections to fail (ie those with exact==true or regex)
> test(e2e): make test pass again

- packages/dm-core-plugins/src/explorer/components/context-menu/NodeRightClickMenu.tsx
- packages/dm-core-plugins/src/explorer/components/dialogs/AppendEntityDialog.tsx
- packages/dm-core-plugins/src/explorer/components/dialogs/NewBlueprintDialog.tsx
- packages/dm-core-plugins/src/explorer/components/dialogs/NewEntityDialog.tsx
- packages/dm-core-plugins/src/explorer/components/dialogs/NewFolderDialog.tsx
- packages/dm-core/src/components/TreeView.tsx
Add the possibility for node wrappers to close or open a node in the tree.
It can be handy for wrappers to be able to extend and close nodes in the tree. For example if you're adding a blueprint to a folder that is closed, it makes sense to open it so that the user can see that the blueprint has been added. The explorer had tried to implement this before (thus the node.expand() calls) but it wasn't working. Now it does.
ref #534
> fix(tree): allow node wrappers to open/close node

- packages/dm-core/src/domain/Tree.tsx
Removes level from TreeNode
Earlier, level was used to create correct indenting of the TreeView. This is no longer needed
ref #534
> refactor(tree): remove unused level prop

- packages/dm-core/src/domain/Tree.tsx
Removing it didn't make anything crash
ref #534
> refactor(tree): remove unused TreeNode iterator

- packages/dm-core/src/domain/Tree.tsx
Removing it didn't seem to make anything crash. I think the operation is covered by the more generic TreeNode.expand()
ref #534
> refactor(tree): remove unneeded root package init

- packages/dm-core-plugins/src/explorer/components/context-menu/getMenuItems.tsx
- packages/dm-core-plugins/src/explorer/components/dialogs/AppendEntityDialog.tsx
- packages/dm-core/src/domain/Tree.tsx
Removes `attribute` from TreeNode class.
Not really needed, and it increases the complexity of the code
#ref #534
> refactor(tree): remove attribute from treenode

- e2e/tests/plugin-table-car_list.spec.ts
#553 fixed the issue with pagination where it was possible to navigate beyond the number of items in the table.
Playwright test had a check for this but commented out until issue was fixed. Therefore uncommenting the check.
> fix: update table test pagination check

- packages/dm-core-plugins/package.json
- packages/dm-core/package.json
Bump eds-core-react to version 0.33.0.
> chore: bump eds version

- e2e/tests/plugin-view_selector-car_garage.spec.ts
EDS added support for aria label to the collapse/expand button, which makes it a lot easier for Playwright to get the element.
> fix: update view-selector test after EDS update

- packages/dm-core/src/components/Pickers/DestinationPicker.tsx
- packages/dm-core/src/components/Pickers/EntityPickerDialog.tsx
- packages/dm-core/src/domain/Tree.tsx
- a list of datasources is now optional when using initFromDataSources
- initFromFolder can handle both paths to packages, documents and attributes
The next steps is to 
1. allow for passing in a list of paths
2. merge these two init functions into one.
ref #534
> feat(tree): allow attribute paths as input

- .github/workflows/create-release-pr.yaml
- .github/workflows/deploy-to-radix.yaml
- .github/workflows/on-main-push.yaml
- .github/workflows/on-release.yaml
* Fixed so that the packages are not tried to be published twice and therefore fail the second time (since it is already uploaded)
* Added the possibility to manually trigger the `on-release` workflow
* Added so that release please is responsible for triggering the  `on-release` after a release is created
> ci: deploy to Radix

- packages/dm-core-plugins/src/header/components/UserInfoDialog.tsx
A one character change so the UserInfoDialog does not crash if the user has no role.
Avoid crashing. Making the code more robust.
none
> fix: UserInfoDialog crash when no roles in token

- packages/dm-core-plugins/src/explorer/components/context-menu/getMenuItems.tsx
- packages/dm-core-plugins/src/form/components/DynamicTable.tsx
- packages/dm-core-plugins/src/form/context/RegistryContext.tsx
- packages/dm-core-plugins/src/form/context/WidgetContext.tsx
- packages/dm-core-plugins/src/form/fields/ObjectField.tsx
- packages/dm-core-plugins/src/form/types.tsx
- packages/dm-core-plugins/src/grid/GridElement.tsx
- packages/dm-core-plugins/src/grid/GridPlugin.tsx
- packages/dm-core-plugins/src/header/HeaderPlugin.tsx
- packages/dm-core-plugins/src/role_filter/RoleFilterPlugin.tsx
- packages/dm-core-plugins/src/view_selector/Content.tsx
- packages/dm-core-plugins/src/view_selector/Sidebar.tsx
- packages/dm-core-plugins/src/view_selector/Tabs.tsx
- packages/dm-core-plugins/src/view_selector/ViewSelectorPlugin.tsx
- packages/dm-core/src/components/AccessControl/ACLOwnerPanel.tsx
- packages/dm-core/src/components/AccessControl/ACLSelect.tsx
- packages/dm-core/src/components/AccessControl/ACLUserRolesPanel.tsx
- packages/dm-core/src/components/AccessControl/AccessControlListComponent.tsx
- packages/dm-core/src/components/DynamicTable.tsx
- packages/dm-core/src/components/EntityView.tsx
- packages/dm-core/src/components/ViewCreator/ViewCreator.tsx
- packages/dm-core/src/context/UiPluginContext.tsx
- packages/dm-core/src/hooks/useRecipe.tsx
- packages/dm-core/src/types.ts
Replaces deprecated type `JSX.Element` with `React.ReactElement`
> refactor: deprecated type

- .github/workflows/create-release-pr.yaml
- .github/workflows/deploy-to-radix.yaml
- .github/workflows/on-main-push.yaml
- .github/workflows/on-release.yaml
- example/src/init.sh
* Remove `--from-config`since the `radixconfig.yaml` is not inside this repository and therefore it does not make sense to have the flag
* Dont use alias when building in Radix (since should use dm-* NPM packages instead)
> fix: skip from config flag

- .github/workflows/on-main-push.yaml
* Only try to publish a package if the version specified in package.json does not exist in NPM registry
> fix: check if package exist before publish

- packages/dm-core/src/hooks/useBlueprint.tsx
- packages/dm-core/src/hooks/useRecipe.tsx
There currently is a bug where the previous recipe is used when selecting a new plugin/app. I'm fairly certain that happens because of some state dependencies that don't work out correctly.
The `useRecipe()` hook is/was dependent on state variables from the `useBlueprint()` hook, but state variables are not updated before a re-render occurs. That means the `useRecipe` hooks is/was always getting the previous values, and not the current ones.
> Fix: Select correct recipes when switching views

- example/app/data/DemoDataSource/recipes/plugins/form/read_only_primitives/readOnlyPrimitives.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/form/simple/simple.recipe.json
* The view creator was not used in the `read only primitives` and `simple` form examples, soI just removed the use of the view creator plugin in these examples.
> refactor: simply recipe by skipping view creator

- packages/dm-core-plugins/src/explorer/ExplorerPlugin.tsx
Makes sure that list entities are rendered as lists.
Not sure this approach is sufficient, but its something..
To render lists as lists
#613
> fix: render lists as lists

- packages/dm-core-plugins/src/form/FormPlugin.tsx
- packages/dm-core/src/hooks/useDocument.test.tsx
- packages/dm-core/src/hooks/useDocument.tsx
* Set default level to 0 for form package and `useDocument` hook
> refactor: adjust default depth level to 0

- .github/workflows/tests.yaml
- e2e/tests/plugin-form-Nested.spec.ts
- e2e/tests/plugin-view_selector-car_garage.spec.ts
- example/app/data/DemoDataSource/recipes/plugins/grid/example/order.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/grid/example/orderItem.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/list/order_example/order.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/list/order_example/orderItem.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/list/task_list/task.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/list/task_list/taskList.recipe.json
- packages/dm-core-plugins/blueprints/list/FunctionalityConfig.json
- packages/dm-core-plugins/blueprints/list/ListPluginConfig.json
- packages/dm-core-plugins/src/form/components/Form.tsx
- packages/dm-core-plugins/src/form/fields/BooleanField.test.tsx
- packages/dm-core-plugins/src/form/fields/NumberField.test.tsx
- packages/dm-core-plugins/src/form/fields/ObjectField.test.tsx
- packages/dm-core-plugins/src/form/fields/StringField.test.tsx
- packages/dm-core-plugins/src/list/ListPlugin.tsx
- packages/dm-core-plugins/src/list/README.md
- remove redundant config values
- set most functionality to be enabled by default
- make use of "sort" and "delete" config values
- error toast when attempting to open in tab when no "onOpen()" was passed to the plugin
Plugins should work and have sane defaults without having to create UiRecipes
closes #616
> fix(listPLugin): sane default config

- example/app/data/DemoDataSource/recipes/apps/signal_app/recipe_links/signals_simple/case.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/grid/example/dashboard.recipe.json
- packages/dm-core-plugins/src/grid/GridElement.tsx
- packages/dm-core-plugins/src/grid/GridPlugin.tsx
the grid positioning is referencing the grid lines, not the columns. Therefor I increment the end by one to reference the "ending line" of the column
closes #638
> fix: make grid columns span correctly

- example/app/data/DemoDataSource/plugins/grid/car_grid/blueprints/TyreList.blueprint.json
- example/app/data/DemoDataSource/plugins/grid/car_grid/raceCenter.entity.json
- example/app/data/DemoDataSource/plugins/grid/car_grid/tyreList.entity.json
- example/app/data/DemoDataSource/recipes/plugins/grid/car_grid/raceCenter.recipe.json
Moved the entity data from the grid´s entity to the list´s entity. This will organise the data inside the actual plugin´s entity, instead of gathering all the data in one large entity (the grid). 
Right now the Grid plugin is unable to resolve UI-recipes that are referenced #639
> test(grid): list with referenced ui-recipe

- e2e/tests/plugin-form-Simple.spec.ts
Use test.step instead of comments to divide different part of the test.
This improves maintainability and better reporting as steps are now grouped.
> fix(test): improving test using test.step

- packages/dm-core/src/context/DMJobContext.tsx
- packages/dm-core/src/services/api/DmJobAPI.ts
remove old base url, throw error if job api url has not been provided
> fix: make job api provider use dm job api url from vite

- packages/dm-core/src/components/ViewCreator/utils.ts
allow scope to be defined in UiRecipes using `self`, `self.attribute`, `.attribute` and `^.attribute`
> fix: allow multiple ways of defining scope

- packages/dm-core/src/components/ViewCreator/utils.ts
Do not allow the use of ^ operator when using scope, throw exception if attempted
e.g. $123.a.b  w/ scope .c. ->  $123.1.b.c
dont allow scope ^.a.b.c
> fix: disallow hat operator in scope

- .github/workflows/integration-tests.yaml
- e2e/playwright.config.ts
- e2e/tests/plugin-list-task_list.spec.ts
- e2e/tests/plugin-table-car_list.spec.ts
- packages/dm-core-plugins/src/view_selector/Content.tsx
- packages/dm-core-plugins/src/view_selector/TabsPlugin.tsx
- packages/dm-core/src/hooks/useList.tsx
* Use production build (dist/) when running tests
* Cache playwright binary dependencies 
* Remove `slowMo` from playwright config
* Added extra expect that seems to make the code more stable (not 100% sure here)
* For `TabPlugin` and `SidebarPlugin`, don't render hidden tabs or sidebar content if not visible.
* Don't set loading false in `useList` plugin after getting the attribute, this makes it only disable loading after both attribute and the actual data is fetched
> test: make e2e stable and faster

- packages/dm-core-plugins/src/grid/GridElement.tsx
Added data-testid to the GridElement based on scope.
Easier to write tests where the Grid is used as the data-testid will allow us pinpoint each plugin inside the grid.
> feat(grid): added test-id to gridelement

- .github/workflows/tests.yaml
- .pre-commit-config.yaml
Adds hooks to run type checks in pre-commit
Save time on not pushing code that will fail CI on types
closes #595
> build: enable type check in pre-commit

- packages/dm-core-plugins/src/list/ListPlugin.tsx
- packages/dm-core/src/components/TreeView.tsx
- packages/dm-core/src/styles/main.css
Changes the icon for opening and closing the list to be a chevron, as that is more appropriate. Also adds some animations, since they're oh so pretty
It pleases me
none
https://github.com/equinor/dm-core-packages/assets/3105885/8bc3e09a-39ff-4686-bf32-961b065c9858
> refactor: change icon on list open/close, and add animations

- example/app/data/DemoDataSource/recipes/plugins/grid/car_grid/raceCenter.recipe.json
Added an example where the reference is not resolved. The same example plugin is now shown as resolved and unresolved, using the same blueprints and entities.
Testing that the resolve flag in ViewConfig works as intended.
> test(grid): added resolve false example

- packages/dm-core/src/components/EntityView.tsx
Just break and wrap long lines for nicer, easier to read error messages.
> fix: wrap recipe errors message in EntityView

- example/docker-compose.yaml
- example/vite.config.ts
- packages/dm-core-plugins/package.json
- packages/dm-core-plugins/src/form/components/AddObjectButton.tsx
- packages/dm-core-plugins/src/form/components/RemoveObjectButton.tsx
- packages/dm-core-plugins/src/form/fields/ArrayField.tsx
- packages/dm-core-plugins/src/form/fields/ObjectField.tsx
* fix: add or remove optional lists
* fix: tab crashes if try to open a list that does not exists (need to add it first)
* refactor: moved `AddObjectButton` and `RemoveObjectButton` into their own files and out from `ObjectField` that was getting to big, and also re-using the buttons in the `ArrayField`.
* refactor: split up `ArrayField` which was too complex, into using several components `PrimitiveList`, `InlineList`, or `OpenList`, instead of everything being one huge component. 
* chore: update DMSS version that includes fix for add optional empty lists 
How it looks like:
UiRecipes exist, so can be removed or opened.
StorageRecipes does not exist, so can add it.
> fix(form): add or remove optional lists

- example/app/data/DemoDataSource/recipes/blueprint.recipe.json
- packages/dm-core-plugins/src/blueprint/BlueprintPlugin.tsx
- packages/dm-core/src/Enums.ts
- Set "blueprint" as the default plugin for "Blueprint"-entities
- Reset value of "default" when changing type of the attribute
- Use a switch to set default value of a boolean
- Only render "contained"-switch on none-primitive types (excluding "any")
- Fixes several bugs with the plugin
none
> fix(blueprint): fix several minor bugs in blueprint plugin

- example/package.json
* REACT_APP_DM_JOB_URL is not in use anymore, remove it from startup script and at the same time the `cross-env` dependency 💥
> chore: remove unused env

- e2e/tests/plugin-grid-car_grid.spec.ts
- example/app/data/DemoDataSource/plugins/grid/car_grid/blueprints/RaceCenter.blueprint.json
- example/app/data/DemoDataSource/plugins/grid/car_grid/raceCenter.entity.json
- example/app/data/DemoDataSource/recipes/plugins/grid/car_grid/raceCenter.recipe.json
Added integration tests for the plugins in the grid example. 
The tests are mainly focusing on verifying that the plugins are showing correctly in the grid, not testing the plugins themselves.
The grid example should probably be expanded with more plugin examples and tests later.
closes #567
> test(grid): testing plugins in grid view

- e2e/tests/plugin-default_recipe.spec.ts
- example/app/data/DemoDataSource/plugins/default_recipe/TableList.entity.json
- example/app/data/DemoDataSource/plugins/default_recipe/blueprints/Form.blueprint.json
- example/app/data/DemoDataSource/plugins/default_recipe/blueprints/Table.blueprint.json
- example/app/data/DemoDataSource/plugins/default_recipe/blueprints/TableList.blueprint.json
- example/app/data/DemoDataSource/plugins/default_recipe/form.entity.json
Added examples using the default DMSS Ui Recipe where there are no dedicated ui recipes.
closes #599
> test: examples using default dmss ui recipe

- packages/dm-core-plugins/src/blueprint/BlueprintPlugin.tsx
- packages/dm-core/src/components/Pickers/BlueprintPicker.tsx
- packages/dm-core/src/utils/truncatePathString.ts
Minor visual improvements
- Adding some icons
- Replacing "select blueprint"-input with button
- Make "add extend blueprint" a one-step, instead of a two-step process
> fix(blueprint): some more polish of the blueprint plugin

- packages/dm-core-plugins/src/list/ListPlugin.tsx
Different icons for opening tabs inline or in tab
> refactor: different icon for opening list in tab or inline

- packages/dm-core-plugins/src/header/components/UserInfoDialog.tsx
Slightly tweaks the user info dialog
> refactor: tweak the user info dialog

- packages/dm-core-plugins/src/job/JobPlugin.tsx
- packages/dm-core/src/hooks/useJob.tsx
Stop polling when status on the polled job is failed or completed.
Polling now stop as long as the job is shown as not running. This is problematic when the polling starts before the job-api is able to change the status to running.
Closes #736
> fix: stop job poll on failed or completed status

- packages/dm-core-plugins/src/index.tsx
- packages/dm-core-plugins/src/role_filter/RoleFilterPlugin.tsx
- packages/dm-core/src/components/EntityView.tsx
* Lazy load plugins, see https://legacy.reactjs.org/docs/code-splitting.html
> refactor: lazy import plugins

- example/app/data/DemoDataSource/recipes/apps/signal_app/recipe_links/signals_simple/case.recipe.json
- packages/dm-core-plugins/blueprints/job/JobConfig.json
- packages/dm-core-plugins/src/job/JobPlugin.tsx
Makes the recurring toggle in the job plugin configurable.
closes #711
> feat: make recurring switch configurable

- e2e/playwright.config.ts
- e2e/tests/plugin-default_recipe.spec.ts
- e2e/tests/plugin-form-Nested.spec.ts
- e2e/tests/plugin-form-Simple.spec.ts
- e2e/tests/plugin-form-model_uncontained-complex_attribute.spec.ts
- e2e/tests/plugin-grid-car_grid.spec.ts
- e2e/tests/plugin-header-roles_header_example.spec.ts
- e2e/tests/plugin-header.spec.ts
- e2e/tests/plugin-view_selector-car_garage.spec.ts
- e2e/tests/plugin-view_selector-roles_school_example.spec.ts
- e2e/tests/signalApp.spec.ts
- example/app/data/DemoDataSource/recipes/plugins/form/nested/carRentalCompany.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/grid/car_grid/carList.recipe.json
- packages/dm-core-plugins/src/form/components/AttributeList.tsx
- packages/dm-core-plugins/src/form/components/Form.test.tsx
- packages/dm-core-plugins/src/form/components/Form.tsx
- packages/dm-core-plugins/src/form/fields/ArrayField.test.tsx
- packages/dm-core-plugins/src/form/fields/ArrayField.tsx
- packages/dm-core-plugins/src/form/fields/ObjectField.tsx
- packages/dm-core-plugins/src/form/fields/StringField.test.tsx
- packages/dm-core-plugins/src/form/test-utils.tsx
- packages/dm-core-plugins/src/form/types.tsx
- packages/dm-core-plugins/src/form/widgets/TextWidget.tsx
- packages/dm-core/src/hooks/useBlueprint.tsx
- packages/dm-core/src/types.ts
- "form"-plugin will now default to use the first uiRecipe in the list of recipes (including "initial")
- If a recipe name was given, but not found --> Raise error.
Fixes a bug where "form" failed to pick a uiRecipe if no name was provided
closes #718
> fix(form): recipe name should be optional in ObjectField

- example/.env.test
there was a 'gh' extra in redirect uri
> fix: remove 'gh' from redirect uri

- packages/dm-core-plugins/src/list/ListPlugin.tsx
Fixes the problem in SIMPOS where cant view signals:
> fix: resolve relative references

- example/app/data/DemoDataSource/recipes/plugins/form/nested/carRentalCompany.recipe.json
- packages/dm-core-plugins/blueprints/form/FormInput.json
- packages/dm-core-plugins/blueprints/form/fields/ArrayField.json
- packages/dm-core-plugins/blueprints/form/fields/ObjectField.json
- packages/dm-core-plugins/src/form/components/AttributeList.tsx
- packages/dm-core-plugins/src/form/fields/ArrayField.tsx
- packages/dm-core-plugins/src/form/fields/AttributeField.tsx
- packages/dm-core-plugins/src/form/fields/ObjectField.tsx
- packages/dm-core-plugins/src/form/types.tsx
Add config to say if inline objects or arrays should be collapsable/expanded by default or not!
> feat(form): configure if fields should be expanded by default

- packages/dm-core-plugins/src/list/ListPlugin.tsx
Changed list icon to be: 
instead of + which was not intuitive of being "open". Plus means add, not open.
> feat: open in tab icon instead of plus in list

- packages/dm-core-plugins/src/list/ListPlugin.tsx
1. Chevron is now right and down, instead of down and up. This is to be consistent with the other usages of chevron in the application. Like how it is used in the tree view. 
2. List title is now clickable as well, not only the chevron. Makes it easier to use.
> feat: list clickable and chevron change

- packages/dm-core-plugins/src/header/HeaderPlugin.tsx
When clicking the header menu, and click away, the header menu now disappears. 
Before you had to click on the menu again to make it go away.
> feat: when click away from header menu it goes away

- example/app/data/DemoDataSource/recipes/plugins/view_selector/roles_school_example/schoolDistrict.recipe.json
- packages/dm-core-plugins/blueprints/view_selector/ViewSelectorItem.json
- packages/dm-core-plugins/src/view_selector/Sidebar.tsx
- packages/dm-core-plugins/src/view_selector/SidebarPlugin.tsx
- packages/dm-core-plugins/src/view_selector/types.tsx
- packages/dm-core-plugins/src/view_selector/useViewSelector.tsx
- packages/dm-core/src/types.ts
- Adds an optional list of "subItem" to the "ViewSelectorConfig". Allowing to configure sub items in the sidebar menu
More compact and effective UI navigation
closes #729
> feat(view_select): add sub menu

- packages/dm-core/src/components/EntityView.tsx
- Use "memo" on the plugin component (meaning it won't rerender unless any props changes
- The new refresh function caused all child components to rerender on mouse enter/leave. This is a performance issue
none
> perf(EntityView): stop plugin rerender on mouseEnter

- example/Dockerfile
* Upgrade node docker image to fix 
```
error vite@5.0.0: The engine "node" is incompatible with this module. Expected version "^18.0.0 || >=20.0.0". Got "19.9.0"
```
> chore: upgrade node docker image

- e2e/tests/plugin-header-roles_header_example.spec.ts
- e2e/tests/plugin-header.spec.ts
- example/app/data/DemoDataSource/recipes/apps/signal_app/recipe_links/containers/equallySpacedSignal.recipe.json
- packages/dm-core-plugins/src/header/HeaderPlugin.tsx
Fixes bug where one can not select application again after switching. 
Did this by changing from eds.Menu to eds.Popover. 
Looks a bit different now as well. 
#771
> fix: Bug where header menu did not appear after switching

- packages/dm-core-plugins/src/job/JobPlugin.tsx
Show the status of the job at all times
Makes it easier to understand that the job is done, running etc. not just failed
Closes #753
> fix: always show status as chip in job plugin

- packages/dm-core/src/components/Dialog.tsx
Bug with EDS Dialog and Dialog actions floating over content when dialog becomes scrollable
closes #752
> fix(Dialog): DialogActions float over content

- packages/dm-core-plugins/src/view_selector/Sidebar.tsx
Make parent menu entries in Sidebar™ not be clickable.
> fix(Sidebar): parnet menu items shouldn't be clickable

- packages/dm-core-plugins/src/job/LogBlock.tsx
Formats the logs from jobs as lines instead of array
> fix: format logs from job as lines

- e2e/tests/plugin-form-Nested.spec.ts
- e2e/tests/plugin-form-model_uncontained-complex_attribute.spec.ts
- e2e/tests/plugin-view_selector-car_garage.spec.ts
- example/app/data/DemoDataSource/recipes/plugins/form/enums/enums.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/form/simple/simple.recipe.json
- packages/dm-core-plugins/blueprints/form/fields/Field.json
- packages/dm-core-plugins/src/form/FormPlugin.tsx
- packages/dm-core-plugins/src/form/components/AttributeList.tsx
- packages/dm-core-plugins/src/form/components/Form.test.tsx
- packages/dm-core-plugins/src/form/components/Form.tsx
- packages/dm-core-plugins/src/form/context/RegistryContext.tsx
- packages/dm-core-plugins/src/form/fields/ArrayField.test.tsx
- packages/dm-core-plugins/src/form/fields/ArrayField.tsx
- packages/dm-core-plugins/src/form/fields/AttributeField.tsx
- packages/dm-core-plugins/src/form/fields/BinaryField.tsx
- packages/dm-core-plugins/src/form/fields/BooleanField.tsx
- packages/dm-core-plugins/src/form/fields/NumberField.test.tsx
- packages/dm-core-plugins/src/form/fields/NumberField.tsx
- packages/dm-core-plugins/src/form/fields/ObjectField.tsx
- packages/dm-core-plugins/src/form/fields/StringField.tsx
- packages/dm-core-plugins/src/form/types.tsx
- packages/dm-core-plugins/src/form/utils/getDisplayLabel.tsx
- packages/dm-core-plugins/src/form/widgets/DateTimeWidget.tsx
- packages/dm-core-plugins/src/form/widgets/NumberWidget.tsx
- packages/dm-core-plugins/src/form/widgets/SelectWidget.tsx
- packages/dm-core-plugins/src/form/widgets/TextWidget.tsx
- packages/dm-core-plugins/src/form/widgets/TypeWidget.tsx
- packages/dm-core-plugins/src/form/widgets/index.ts
* Avoid prop drilling, only pass what is needed
* Use context to provide the `FormConfig` to fields, instead of passing them down as props (the read only and show expanded setting)
* Add util `getDisplayLabel` to provide a way to have common labels for all fields, instead of passing it down as a prop
* Just pass the `attribute` down instead of splitting it up and passing down parts of it
* Make `StringField` less complex by
* Add `NumberWidget` to handle numbers
* Add  `DateTimeWidget` to handle date time
> **NOTE**: The overall goal of this PR is to make it clear what props are needed for each field (StringField, NumberField etc.). This PR focuses mostly on primitive fields.  The PR is quite large already, since we are renaming and removing stuff, so will not include everything in this …
> refactor: avoid prop drilling

- packages/dm-core-plugins/src/form/components/SelectReference.tsx
- packages/dm-core-plugins/src/form/fields/ArrayField.tsx
- packages/dm-core-plugins/src/form/fields/ObjectField.tsx
- packages/dm-core-plugins/src/form/templates/ArrayComplexTemplate.tsx
- packages/dm-core-plugins/src/form/templates/ArrayPrimitiveTemplate.tsx
- packages/dm-core-plugins/src/form/templates/ObjectModelContainedTemplate.tsx
- packages/dm-core-plugins/src/form/templates/ObjectModelUncontainedTemplate.tsx
- packages/dm-core-plugins/src/form/templates/ObjectStorageUncontainedTemplate.tsx
- packages/dm-core-plugins/src/form/types.tsx
- packages/dm-core-plugins/src/form/utils/isPrimitiveType.tsx
* Add templates to divide the code more up and more easy to understand/maintaine
> **NOTE**: This PR is based on #807, so that needs to be taken in first.
> refactor: add templates to divide code more up

- example/app/data/DemoDataSource/recipes/apps/ExampleApplication/ExampleApplication.recipe.json
- packages/dm-core-plugins/src/header/HeaderPlugin.tsx
- Adds "key" with recipe name for <UiPlugin>. This is needed as the other props might not change.
- bug
closes #https://github.com/equinor/dm-app-simpos/issues/57
> fix(header): Did not rerender views since key was not set on <UiPlugin>

- e2e/tests/plugin-form-model_uncontained-complex_attribute.spec.ts
- e2e/tests/plugin-header.spec.ts
- packages/dm-core-plugins/src/header/HeaderPlugin.tsx
- packages/dm-core-plugins/src/header/components/AppSelector.tsx
after tailwind made h2 and h4 not styled anymore
> fix: header ui

- e2e/tests/plugin-form-Media_viewer.spec.ts
- e2e/tests/plugin-form-model_uncontained-complex_attribute.spec.ts
Added some extra asserts and other changes to try to make the test more stabile.
If the media_viewer test still is flaky, we could try to use expect.toPass to retry the assertions. The reason the test was flaky seem to be that the test proceeded before the image was completely loaded.
Tests were flaky.
> fix: model uncontained and media_viewer tests

- packages/dm-core/src/components/Pickers/EntityPickerDialog.tsx
* Close the model after calling on an update to make the test more stable.
> test: close model after called on change

- packages/dm-core-plugins/src/form/widgets/TextareaWidget.tsx
- packages/dm-core-plugins/src/role_filter/RoleFilterPlugin.tsx
- packages/dm-core/src/components/AccessControl/ACLOwnerPanel.tsx
- packages/dm-core/src/components/AccessControl/AccessControlListComponent.tsx
- packages/dm-core/src/components/Table/TableHead/TableHead.tsx
- packages/dm-core/src/components/Table/TableRow/TableRow.tsx
Changes the usage of icon to use the data prop instead of the name
> refactor: use Icon data instead of name

- packages/dm-core/src/components/Pickers/Datepicker/Calendar.tsx
- packages/dm-core/src/components/Pickers/Datepicker/Datepicker.tsx
- close picker on click outside
- set date and month to initial
- accept empty value on start
closes #883
> fix: fix some bugs

- packages/dm-core-plugins/src/form/components/NumberFieldWithoutArrows.tsx
- packages/dm-core-plugins/src/form/widgets/DimensionalScalarWidget.tsx
- packages/dm-core-plugins/src/form/widgets/NumberWidget.tsx
> feat: Removes up-down arrows in numberfields

- packages/dm-core-plugins/src/form/templates/ArrayComplexTemplate.tsx
- packages/dm-core-plugins/src/form/templates/ArrayPrimitiveTemplate.tsx
- packages/dm-core-plugins/src/form/templates/ObjectModelContainedTemplate.tsx
- packages/dm-core-plugins/src/form/templates/ObjectModelUncontainedTemplate.tsx
Added "collapse" to the titles for some expandable buttons. These only had the title "Expand" which was misleading when already expanded.
> fix: added titles to expandable buttons

- e2e/tests/plugin-table-car_list.spec.ts
- packages/dm-core-plugins/src/grid/GridElement.tsx
- packages/dm-core-plugins/src/grid/GridItems.tsx
- packages/dm-core-plugins/src/grid/GridPlugin.tsx
- packages/dm-core-plugins/src/table/TablePlugin.tsx
- packages/dm-core/src/components/Table/Table.tsx
- packages/dm-core/src/components/Table/TableRow/TableRow.tsx
- packages/dm-core/src/components/Table/types.ts
* `TablePlugin` listen to onSubmit in expanded or opened views
* `GridPlugin` passes down `onSubmit` and `onChange` to grid items
> feat: update table on any submits in expanded or table views

- e2e/tests/plugin-table-car_list.spec.ts
Fixed several issues with the table test
- Test was sometimes adding a new line in the table before the table content was fully loaded, causing the added line not to show. Added an extra expect to make sure the content are fully loaded before proceeding the test. 
- Incorrect expect assertion (checked an element not to be visible, when it should be visible)
- Testing the pagination was incorrect, but sometimes run successful anyway (especially locally) because test proceeded to early.
> fix: table test issues

- packages/dm-core-plugins/src/form/templates/ObjectModelContainedTemplate.tsx
- packages/dm-core-plugins/src/form/templates/ObjectModelUncontainedTemplate.tsx
- packages/dm-core-plugins/src/form/templates/ObjectStorageUncontainedTemplate.tsx
* Default to expand if no `onOpen` function is available
> fix: default able to expand if no open passed

- packages/dm-core-plugins/src/list/ListPlugin.tsx
- packages/dm-core/src/components/Table/TableRow/TableRow.tsx
Use index and attribute name when opening object without name in new tab
Name is often not a required attribute
Close #860
> fix: default tab name on open

- example/src/plugins/table/TestUseListPlugin.tsx
- packages/dm-core/src/components/EntityView.tsx
- Since `Object.is({}, {}) is false.`, the memo wrapped UiPlugins did not work.
- Solved by passing the whole "recipe" object to memoized function, before creating a default {}
- Rerender on hover breaks some child components that can not rerender at any point (plotly etc.)
closes #https://github.com/equinor/dm-app-simpos/issues/65
> fix: Creating new config object on every render breaks memo

- e2e/tests/plugin-form-UncontainedObject.spec.ts
Updated the test for uncontainedObject after added expand feature (#928).
> fix: update uncontained object test with expand

- e2e/tests/plugin-form-dimensional_scalar.spec.ts
Test is still unstable, trying to add more expects.
If this does not work I suspect same issue as with the model uncontained test (#847)
> fix: dimensional scalar test stabilisation

- e2e/tests/plugin-default_recipe.spec.ts
- packages/dm-core-plugins/src/form/components/ExpandChevron.tsx
- packages/dm-core-plugins/src/form/templates/ArrayComplexTemplate.tsx
- packages/dm-core-plugins/src/form/templates/ObjectModelContainedTemplate.tsx
- packages/dm-core-plugins/src/form/templates/ObjectModelUncontainedTemplate.tsx
- packages/dm-core-plugins/src/form/templates/ObjectStorageUncontainedTemplate.tsx
- packages/dm-core-plugins/src/form/templates/shared/FormTemplate.tsx
- packages/dm-core-plugins/src/form/templates/shared/utils.ts
1. New icon for model uncontained. Link
2. Better ui for all objects in form. 
- whole thing is clickable. 
- shows with underline if opens in tab, shows with chevron if expand
- ctrl + click / comand + click to open instead of expand
3. Also made new ui design include complex arrays. 
5. A bug fix with the onOpen sometimes finding wrong reference
> feat: complex attribute, bug fix, and new icon for model uncontained

- packages/dm-core/src/components/Table/TableRow/TableRow.tsx
Makes the table rows colored slightly differently based on their index. Hover style disappeared though, and I can't see the declaration of `...dragProps` 🤔 @awesthouse where are those defined?
> refactor: even-odd coloring on table rows

- packages/dm-core-plugins/src/form/components/Form.tsx
* Fix the bug that nested forms that are inline (expanded) do not update themselves.
The fix was to include them in the payload that was sent to the API.
> fix: update nested form

- packages/dm-core-plugins/src/form/components/PrimitiveArray.tsx
Remove a newly added header to the primitive array, so that it looks better. 
Now it looks like:
> feat: remove empty header form primitive array

- packages/dm-core-plugins/src/form/fields/StringField.tsx
- packages/dm-core/src/components/Pickers/Datepicker/Datepicker.tsx
- packages/dm-core/src/hooks/useClickOutside.tsx
- Sets the time to 12:00 when selecting a date, and there is no time set.
- Opens the panel above if there is no space beneath.
> refactor: improve default time value, and open above if no space

- packages/dm-core-plugins/src/job/CrateFromRecipe.tsx
- packages/dm-core-plugins/src/job/JobControlButton.tsx
Bug where job control button in JobPlugin remained disabled when the user clicks cancel on the confirm delete prompt
> bug: re enable job controls on remove cancelation

- packages/dm-core-plugins/src/form/widgets/DateTimeWidget.tsx
* Fix that the DateTimeWidget does not crash if no config is provided
> fix: form crash

- packages/dm-core-plugins/src/list/ListPlugin.tsx
* fix: the item need to be saved it can be expanded
> fix: item must be saved before can expand

- packages/dm-core-plugins/src/view_selector/Sidebar.tsx
> fix: select subitem when parent has no viewconfig

- packages/dm-core-plugins/src/list/ListPlugin.tsx
- packages/dm-core/src/components/Table/TableRow/TableRow.tsx
Where objects have name field as empty string, use attribute + index in the generated viewItem that is sendt to the viewSelector
viewSelector shows empty string as tab/sidebar label when name is empty string
> fix: replace name which is empty string with attribute + index

- example/app/data/DemoDataSource/recipes/apps/signal_app/recipe_links/signalApp.recipe.json
- example/app/data/DemoDataSource/recipes/apps/signal_app/recipe_links/signals_simple/study.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/view_selector/car_infosys/car.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/view_selector/car_infosys/carGarage.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/view_selector/car_infosys/owner.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/view_selector/car_infosys/technical.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/view_selector/roles_school_example/school.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/view_selector/roles_school_example/schoolDistrict.recipe.json
- packages/dm-core-plugins/blueprints/view_selector/ViewSelectorItem.json
- packages/dm-core-plugins/src/view_selector/Sidebar.tsx
- packages/dm-core-plugins/src/view_selector/Tabs.tsx
- packages/dm-core-plugins/src/view_selector/types.tsx
- packages/dm-core-plugins/src/view_selector/useViewSelector.tsx
View selector will display the eds icon in the viewselector item instead of the one in viewconfig
To have the possiblity to both control the displayed icon in the sidebar and to not change view when clicking the sidebar
> fix: optional eds icon in viewselectoritem

- packages/dm-core-plugins/src/data-grid/DataGridPlugin.tsx
Uses correct fieldName in payload, not hard-coded field "data"
Trying to post to data field, when it might not exist
> fix: use field name in payload

- example/app/data/DemoDataSource/recipes/plugins/form/nested/carRentalCompany.recipe.json
- packages/dm-core-plugins/blueprints/form/FormInput.json
- packages/dm-core-plugins/src/form/components/Form.tsx
- packages/dm-core-plugins/src/form/types.tsx
Add the options for compact submit buttons, for use when there are many mini-forms. 
Is a flag in formConfig. 
compactButtons : boolean
> feat: compactable form buttons

- example/app/data/DemoDataSource/plugins/form/nested/myCarRentalCompany.entity.json
- example/app/data/DemoDataSource/recipes/plugins/form/nested/car.recipe.json
- packages/dm-core-plugins/src/list/ListPlugin.tsx
- Allow ListPlugin to shrink down at the minimum as wide as its content
- Use flexbox on list items (rows)
Closes #991
> fix: allow list header to grow with flexbox

- e2e/tests/plugin-form-Nested.spec.ts
- e2e/tests/plugin-list-task_list.spec.ts
- example/app/data/DemoDataSource/recipes/plugins/form/nested/car.recipe.json
- packages/dm-core-plugins/blueprints/list/ListPluginConfig.json
- packages/dm-core-plugins/src/list/Components.tsx
- packages/dm-core-plugins/src/list/ListPlugin.tsx
Made a flag to control list compactness. 
Either list is compact or "normal" 
Also made the overflow make sense, with overflow ellipsis if the list attributes span too far, and no overflow. 
Compared to non-compact:
> fix: compact list

- packages/dm-core-plugins/src/job/CrateFromRecipe.tsx
Avoid overwriting default schedule from new job with empty schedule
Before the recurring job has been created, its schedule is empty by default. The cron configuring component sets a default cron string, which is then overwritten in state by the empty schedule
> fix: empty schedule overwriting default cron string

- packages/dm-core-plugins/src/list/ListPlugin.tsx
- packages/dm-core/src/components/Table/Table.tsx
FIX templates for list
- Makes it so uncontained list does not try to use templates, which caused errors. 
- Also makes contained use template[0] if there is only one template provided. 
REFACTOR templates for table
- code here was a bit messy, so refactored it to same pattern as used for lsit
> fix: error when selecting templates for uncontained

- example/app/data/DemoDataSource/recipes/plugins/form/nested/car.recipe.json
- packages/dm-core-plugins/blueprints/list/ListPluginConfig.json
- packages/dm-core-plugins/src/form/templates/ArrayComplexTemplate.tsx
- packages/dm-core-plugins/src/list/Components.tsx
- packages/dm-core-plugins/src/list/ListPlugin.tsx
- packages/dm-core/src/components/Pagination/Pagination.tsx
Config to set default pagination. 
- is put into sorted list of paginationOptions
- if numItems < Min(defaultPaginationSize, selectedPaginationSize) then don't show pagination selector. 
Video of how it works: 
https://jam.dev/c/885b812e-70e2-4a17-b4a7-5a84042f13f5
> Feat: better list padding + default pagination view

- example/app/data/DemoDataSource/recipes/plugins/list/task_list/task.recipe.json
- packages/dm-core-plugins/src/list/ListPlugin.tsx
Babak said default number of items should be 10
> fix: default items per page should be 10

- packages/dm-core-plugins/src/header/components/AboutDialog.tsx
- packages/dm-core-plugins/src/header/components/UserInfoDialog.tsx
Added a close button in the upper right corner for UserInforDialog and AboutDialog.
More user friendly to have an explicit close button, besides clicking outside of the dialog box.
> feat: added close button to userinfo and about dialogs

- packages/dm-core-plugins/src/header/components/UserInfoDialog.tsx
Reset to original user role when closing the dialog box without saving.
When you select a new role but closes the dialog without saving, the new value was still selected when it should have been reset to the original state.
The fix applies for both ways of closing the dialog box. Either by using the "X" or by clicking outside of the box.
> fix: reset role state when closing without saving

- packages/dm-core/src/components/Table/TableRow/TableRow.tsx
Use a deterministic key to open tabs
Table duplicates tabs because a different viewId is used for each open event
Closes #1055
> fix: table opens too many tabs

- example/app/data/DemoDataSource/plugins/list/templates/task1.entity.json
- example/app/data/DemoDataSource/plugins/list/templates/uncontainedTaskList.entity.json
- packages/dm-core-plugins/src/list/ListPlugin.tsx
- packages/dm-core/src/components/TreeView.tsx
- packages/dm-core/src/utils/addressUtilities.test.ts
- packages/dm-core/src/utils/addressUtilities.ts
- ListPlugin's "selectFromScope" can now be a relative address
- Fixes a bug where error nodes in Tree where shown as a folder or document
- Implement a new "resolveRelativeAddress" that is simpler to use (should remove old one later)
- Fix some test entities which had duplicated $id's
closes #1053
> fix(ListPlugin): 'selectFromScope' support relative addresses

- packages/dm-core-plugins/src/list/ListPlugin.tsx
- packages/dm-core/src/components/Table/TableRow/TableRow.tsx
Prioritieses entitty label above enity name when generating label for viewSelectorItem
Requested feature
Closes #1064
> fix: select entity label as view label

- packages/dm-core-plugins/src/view_selector/useViewSelector.tsx
- packages/dm-core/src/components/Table/TableRow/TableRow.tsx
Updates the tab (viewItem) with the latest state onOpen (e.g. with new index when position has changed after delete)
Opening tab after delete does not update the index
Closes #1065
> fix: update existing viewitem on add

- packages/dm-core-plugins/src/list/ListPlugin.tsx
- packages/dm-core/src/components/Table/Table.tsx
1. Uses the new hook "usePagination" in table as well, that fixes an old pagination bug
- The bug was that being on last page and chaning items per page made pagination overflow. 
2. Fix sorting bug: 
- Makes table jump to page 0 when sorting. Earlier sorting put the first elements on the top of the current page, not the top of the whole table, which was a bug.
> Fix: 2 table pagination bugs

- packages/dm-core/src/components/Pickers/EntityPickerDialog.tsx
- packages/dm-core/src/utils/variables.tsx
1. Entity picker dialog is now bigger
2. Entity picker buttons are right adjusted. 
3. Entity picker overflow makes more sense with a sroll, and a hline that separates buttons from content.
> feat: entity picker upgrades

- .github/workflows/on-main-push.yaml
* they have started to use string for releases_created, see https://github.com/google-github-actions/release-please-action/issues/912
> ci: only publish on deploy

- packages/dm-core/src/components/MediaContent.tsx
- packages/dm-core/src/utils/filetypes.ts
- The paragraph was split into 3 parts, looking very weird.
- Some missing file formats (jpg!)
> fix: bad line break in p-tag. Missing image formats

- packages/dm-core/src/components/Table/TableRow/TableCell/TableCell.tsx
- packages/dm-core/src/components/Table/types.ts
When value is 0 in tablecell show the actual zero instead of false value placeholder
0 is equivalent to false, so the check doesn't work for numbers where we want to show 0 values as actual 0s
> fix: show number 0 values as actual 0s

- e2e/tests/plugin-explorer.spec.ts
- packages/dm-core-plugins/src/explorer/components/dialogs/NewEntityDialog.tsx
- packages/dm-core/src/domain/Tree.ts
Adds name text input to new entity dialogue if blueprint has name attribute
- Fall back to "new_entity" as name if name field is empty when creating
Closes #1063
> feat: name in new entity dialoig

- packages/dm-core-plugins/src/list/ListPlugin.tsx
- check for scope before trying to resolve potentially undefined
bug
fixes this:
> fix(list): check for scope before trying to resolve potentially undefined

- example/app/data/DemoDataSource/recipes/plugins/form/nested/carRentalCompany.recipe.json
- packages/dm-core-plugins/blueprints/form/fields/ObjectField.json
- packages/dm-core-plugins/src/form/templates/ObjectModelContainedTemplate.tsx
- packages/dm-core-plugins/src/form/templates/ObjectModelUncontainedTemplate.tsx
- packages/dm-core-plugins/src/form/types.tsx
1. form config "hideDelete" makes entity un-deletable even if it is optional 
2. Currently only for storage Contained
> feat: can hide delete now

- packages/dm-core-plugins/src/job/JobLogsDialog.tsx
- packages/dm-core-plugins/src/job/LogBlock.tsx
1. Removed horisontal scrolling in logs, made it wrap instead. 
2. Removed "double" vertical scroll bars. So only has for the logs now, not the entire dialog as well.
How it was before: 
https://jam.dev/c/70eddea3-ded6-4e27-b95a-7911824df8b6
How it is now: 
https://jam.dev/c/a6a9fe01-4b84-446b-a559-039252ce1340
> fix: logs viewer scrolling

- e2e/tests/plugin-explorer.spec.ts
Expanded test to include checking if the "create" button is disabled when trying to create an entity using a blueprint with a required name field.
#1116
> test(explorer): create entity with required name

- e2e/tests/plugin-form-Media_viewer.spec.ts
- example/app/data/DemoDataSource/plugins/media_viewer/mediaViewerGIF.entity.json
- example/app/data/DemoDataSource/plugins/media_viewer/mediaViewerIMG.entity.json
- example/app/data/DemoDataSource/recipes/plugins/mediaViewer/mediaViewer.recipe.json
- packages/dm-core-plugins/blueprints/media_viewer/MediaViewerConfig.json
- packages/dm-core/src/components/MediaContent.tsx
Make showMeta optional and default to false
Closes #1095
> fix: optional showmeta for mediaviewer

- example/app/data/DemoDataSource/plugins/form/tests/blueprints/primitivearray.blueprint.json
- example/app/data/DemoDataSource/plugins/form/tests/primitivearray.entity.json
- example/app/data/DemoDataSource/recipes/plugins/form/tests/primitivearray.recipe.json
- packages/dm-core-plugins/src/form/components/PrimitiveArray.tsx
Use react hook from context to manipulate form state when deleting item in primitive array
Bug where primitive array is not updated correctly when deleting while in dirty state
Closes #1073
> fix: use form state to update entity

- packages/dm-core-plugins/src/form/templates/ArrayPrimitiveListTemplate.tsx
The tooltip i was placed below the header row
Now it looks like this.
> fix: ui that tooltip was placed wrong

- packages/dm-core/src/components/Table/Table.tsx
- packages/dm-core/src/components/Table/TableHead/TableHead.tsx
- packages/dm-core/src/components/Table/TableRow/TableCell/TableCell.tsx
1. Jumps to last page when adding a new element. 
2. Ui Changes: 
Open icon slightly smaller. 
Chevron to the left side is now primary color (for consistency). 
Cell with chevron is not so big anymore. 
How it is now: 
How is was before:
> fix: minor ui changes to icons in table

- example/app/data/DemoDataSource/recipes/plugins/data_grid/default/default.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/data_grid/multiple_primitives/multiplePrimitives.recipe.json
- packages/dm-core-plugins/src/data-grid/DataGrid.tsx
- packages/dm-core-plugins/src/data-grid/DataGridActions/DataGridActions.tsx
- packages/dm-core-plugins/src/data-grid/DataGridPlugin.tsx
- packages/dm-core-plugins/src/data-grid/HeaderCell/HeaderCell.tsx
- packages/dm-core-plugins/src/data-grid/styles.ts
- packages/dm-core-plugins/src/data-grid/types.ts
- packages/dm-core-plugins/src/data-grid/utils.ts
- Actually reverse data in plugin before passing it to DataGrid component, reverse back before saving
- columnLabels will always be columnLabels, rowLabels will always be rowLabels
- No need to reverse data before exporting data
- Added two more examples for testing printDirection in single-primitive datagrids
- Simplifies a lot of the functionality based on printDirection
- Used to flip table only using css, meaning that HTML-markup and what was viewed was different - not great for accessibility (reading direction, tabbing happened top->down, not left->right as it should)
- columnLabels and rowLabels switching places and meaning based on printDirection was confusing to user - now it's constant. We only flip the data, not the table itself. 
#998
> refactor: actually reverse data instead of using css

- e2e/tests/plugin-form-dimensional_scalar.spec.ts
- example/app/data/DemoDataSource/recipes/plugins/form/nested/carRentalCompany.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/form/uncontained/company.recipe.json
- packages/dm-core-plugins/blueprints/form/fields/Field.json
- packages/dm-core-plugins/src/form/components/PrimitiveArray.tsx
- packages/dm-core-plugins/src/form/fields/NumberField.tsx
- packages/dm-core-plugins/src/form/fields/StringField.tsx
- packages/dm-core-plugins/src/form/widgets/common/StyledInputFields.tsx
Adding tooltip to "Field" so that one can have tooltips on normal input fields as well.
> fix: adding tooltip

- packages/dm-core-plugins/src/form/widgets/CheckboxWidget.tsx
Earlier tooltip was to the right of the whole box.
> Fix: tooltip placement checkbox

- packages/dm-core/src/hooks/useList/useList.tsx
- packages/dm-core/src/hooks/useList/utils.ts
- replace temporary template resolver with common "relativeAddressResolver"
- The old resolver did not support all types of relative addresses
> fix: replace temporary template resolver with common

- packages/dm-core-plugins/tsconfig.json
- Don't include files from outside package. That caused the build dist folder to have an unexpected structure
- All imports from dm-core-plugins failed
> fix: adding files from outside package created bad dist structure

- example/app/data/DemoDataSource/plugins/form/hyperlinks/LinkForm.blueprint.json
- example/app/data/DemoDataSource/plugins/form/hyperlinks/LinkForm.entity.json
- example/app/data/DemoDataSource/recipes/plugins/form/hyperlinks/LinkForm.recipe.json
- example/docker-compose.yaml
- packages/dm-core-plugins/src/form/widgets/HyperlinkWidget.tsx
Url type can now be used with HyperlinkWidget, as well as with simple strings.
> fix: URL type can be used with hyperlinkwidget

- packages/dm-core/src/Enums.ts
- packages/dm-core/src/components/CopyLinkDialog.tsx
- packages/dm-core/src/types.ts
- packages/dm-core/src/utils/setMetaInDocument.ts
- Override text in copy/link popup (so it can be used for "publishing")
- On copy, update entities _meta_
- Option to hide config of values that are provided
closes #1148
> feat: CopyDialog can now hide provided fields and overwrite title

- packages/dm-core/src/hooks/useList/useList.test.tsx
- packages/dm-core/src/hooks/useList/useList.tsx
* Set depth to 1 to keep the references when create entities from templates
> fix: set depth to template to 1

- packages/dm-core/src/hooks/useList/useList.test.tsx
- packages/dm-core/src/hooks/useList/useList.tsx
Fixes the problem that values are not shown in list:
> fix: need to resolve more to get attributes

- packages/dm-core-plugins/src/form/templates/ObjectModelContainedTemplate.tsx
- When constructing the idReference to children in "Form/ObjectField", append attributeName, not namePath since namePath can have multiple "levels"
Profile is back
- seconds level form contained object could not be found because of a badly constructed "idReference"
> fix(form): bad idRef concat for 2-nd-child

- packages/dm-core/src/components/Pickers/Datepicker/Calendar.tsx
- packages/dm-core/src/components/Pickers/Datepicker/Datepicker.tsx
Welcome to my pr. 
This changes 2️⃣ things: 
1. Slight different view for the highlighted dates that have data. 
3. Pass up which year/month that is currently in the view. 
Earlier the only thing the Calendar/Datepicker told the parent about was which date is currently selected. 
But we need also to know what month is currently in the View. 
This is used in SIMPOS to fetch the dates for this month that have any data. 
We use this to highlight the dates with data, without having to fetch all dates for the whole platform that might have data. So we scope only down to the current view for performance reasons.
> feat: pass up selected month

- packages/dm-core/src/components/Pickers/Datepicker/Calendar.tsx
- packages/dm-core/src/components/Pickers/Datepicker/Datepicker.tsx
1. Center calenar icon so it looks better.  Before it was offset by 0.25rem
2. Data dots are now slightly larger to make them easier to see.
> fix: datepicker slight ui changes

- e2e/playwright.config.ts
- e2e/tests/plugin-default_recipe.spec.ts
- e2e/tests/plugin-explorer.spec.ts
- e2e/tests/plugin-form-model_uncontained-complex_attribute.spec.ts
- Default_recipe: Added a few extra asserts to make the test more robust. Removed test.step as it was unnecessary here.
- Plugin-explorer: Added testing of deleting a entity. This also makes it possible to rerun this test locally without needing to reset app.
- Model-uncontained: The last assert was previously removed because it often failed, but it then also removed checking that we actually could update the model. The assert should be there. Added waiting for api request before proceeding which hopefully solves the previous flakiness.
- Config: Changed tracing to retain on failure as we are not doing any retries in the pipeline. Hopefully this will make it easier to debug as the video often ends to early.
> fix: minor changes to some e2e tests and config

- packages/dm-core-plugins/src/job/CronJob.tsx
- packages/dm-core-plugins/src/job/DateRangePicker.tsx
- packages/dm-core-plugins/src/job/JobControl.tsx
- packages/dm-core-plugins/src/job/JobCreate.tsx
- packages/dm-core-plugins/src/job/common.tsx
- packages/dm-core-plugins/src/job/templateEntities.ts
- Default endDate is 1 year ahead
- The "toggle recurring" is hidden for already created jobs
- Disable job config while a job is running
- When using a runner template with recurring jobs, make sure to updated the nested "applicationInput" field
- Don't crash on partial provided default schedule
- Throw error if plugin receives anything that is not a Job entity
- Set "triggeredBy" info in job when starting
bugs
none
> fix(job): several minor bug fixes

- packages/dm-core/src/components/Pickers/EntityPickerDialog.tsx
- packages/dm-core/src/components/TreeView.tsx
- TreeNodes that are lists can not be selected in "EntityPicker"
- Clicking on the Node/Expand button itself, does not select the entity, only expand it.
closes #1188
> fix(entityPicker): hide checkbox for list nodes

- packages/dm-core/src/components/Loading.tsx
So the loading spinner was not so good. 
1. Loaded very 'quickly', making loading seem messy. 
2. Was centered, and made things seem to jump around when loading multiple plugins on the screen. 
3. Was very big, and caused a lot of attention. 
So I made the following changes. 
1. It does not appear immediately, only after loading for 300ms. This is so that components that do load very quickly will not jump around so much. 
2. Made it smaller. 
3. Made it align to top left, so less "jumping around".
> fix: loading ui improvements

- packages/dm-core/src/components/Table/TableRow/TableRow.tsx
Not gray anymore when you hover over expanded stuff in table. 
Large components would have background gray which was kinda annoying. 
https://jam.dev/c/351969d6-543a-4b87-b8b5-eb5739ad9069
> fix: table hover gray no more

- example/.env.local
- example/src/index.tsx
- packages/dm-core/src/context/DMSSContext.tsx
* When developing, it is nice to be able disable to blueprint cache
> chore: disable blueprint cache by config

- example/app/data/DemoDataSource/plugins/responsive_grid/example/blueprints/Dashboard.blueprint.json
- example/app/data/DemoDataSource/plugins/responsive_grid/example/blueprints/Nested.blueprint.json
- example/app/data/DemoDataSource/plugins/responsive_grid/example/blueprints/Order.blueprint.json
- example/app/data/DemoDataSource/plugins/responsive_grid/example/blueprints/OrderItem.blueprint.json
- example/app/data/DemoDataSource/plugins/responsive_grid/example/blueprints/Product.blueprint.json
- example/app/data/DemoDataSource/plugins/responsive_grid/example/dashboardExample.entity.json
- example/app/data/DemoDataSource/plugins/responsive_grid/example/productExample.entity.json
- example/app/data/DemoDataSource/recipes/plugins/responsive_grid/example/dashboard.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/responsive_grid/example/nested.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/responsive_grid/example/order.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/responsive_grid/example/orderItem.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/responsive_grid/example/product.recipe.json
- packages/dm-core-plugins/blueprints/responsive_grid/ColumnItem.json
- packages/dm-core-plugins/blueprints/responsive_grid/ColumnSize.json
- packages/dm-core-plugins/blueprints/responsive_grid/ResponsiveGridPluginConfig.json
- packages/dm-core-plugins/blueprints/responsive_grid/RowItem.json
- packages/dm-core-plugins/blueprints/responsive_grid/package.json
- packages/dm-core-plugins/package.json
- packages/dm-core-plugins/src/index.tsx
- packages/dm-core-plugins/src/responsive_grid/ResponsiveGridPlugin.tsx
- packages/dm-core-plugins/src/responsive_grid/types.ts
- packages/dm-core-plugins/src/view_selector/Sidebar.tsx
- packages/dm-core-plugins/src/yaml/YamlPlugin.tsx
* Add a responsive layout grid that adapts to screen size ensuring consistency across layouts
* Added logic that minimizes the sidebar on smaller screens.
https://github.com/equinor/dm-core-packages/assets/1190419/096294f4-268f-4fa9-8f75-2c07c765eda4
https://github.com/equinor/dm-core-packages/assets/1190419/0056b9c6-9b95-47fc-b94e-3a209c4e41cf
An example configuration can look like this:
```json
"initialUiRecipe": {
"name": "Dashboard",      
"type": "CORE:UiRecipe",
"plugin": "@development-framework/dm-core-plugins/responsive_grid" 
"config": {
"type": "PLUGINS:dm-core-plugins/responsive_grid/ResponsiveGridPluginConfig",
"rows": [
{
"type": "PLUGINS:dm-core-plugins/responsive_grid/RowItem",
"columns": [
{
"type": "PLUGINS:dm-core-plugins/responsive_grid/ColumnItem",
"viewConfig": { …
```
> feat: add responsive grid plugin

- packages/dm-core/src/components/EntityView.tsx
- packages/dm-core/src/components/RefreshButton.tsx
So during Memoization of the UIplugin, lots of the refresh button code was deleted for some reason. 
Therefore we now make refresh button great again 🧢
1. Made it appear as it should
2. Fixed a bit on the UI: 
- Is not transparent all the time, more visible, since it is used only a few places in the application. 
- Makes refresh content when hover refresh button to highlight what is refreshed by the button. 
- A bit better border around refresh content
> fix: make refresh button great again (it wasn't working)

- example/app/data/DemoDataSource/plugins/job/recurringReverseJob.json
- example/app/data/DemoDataSource/recipes/recurringJob.recipe.json
- packages/dm-core-plugins/src/job/CronJob.tsx
- packages/dm-core-plugins/src/job/JobControl.tsx
- packages/dm-core-plugins/src/job/JobCreate.tsx
- packages/dm-core-plugins/src/job/common.tsx
- packages/dm-core-plugins/src/job/templateEntities.ts
- "ConfigureSchedule"-component now loads and parses the set cron-string to populate the config controls
This required a medium sized refactoring of the whole thing... :/
Also, advanced view comes with a disclamer in red
- Bad UX that the set schedule is not shown
> fix(job): simple schedule control not loading existing cron

- example/app/data/DemoDataSource/plugins/form/primitive_arrays/blueprints/PrimitiveArrays.blueprint.json
- example/app/data/DemoDataSource/plugins/form/primitive_arrays/primitiveArrays.entity.json
- example/app/data/DemoDataSource/recipes/plugins/form/primitive_array/PrimitiveArray.recipe.json
- packages/dm-core-plugins/src/form/fields/ArrayField.test.tsx
- packages/dm-core-plugins/src/form/fields/ArrayField.tsx
- packages/dm-core-plugins/src/form/templates/ArrayPrimitiveDataGridTemplate.tsx
- Support creating empty primitive arrays based on dimensions in PrimitiveArray field.
- Added new form to test all use-cases for dimensions and optional/required of primitive arrays in form
Haven't added support yet for creating arrays and 2D arrays in PrimitiveArrays and empty arrays with the correct dimensions and length are needed for the DataGrid component so that user can just input values. We also restrict add and delete functionality of rows and columns based on dimensions so the dimensional arrays have to be correct on creation.
#1147
> feat: support create primitive arrays based on dimensions in form

- packages/dm-core/src/components/MediaContent.tsx
- packages/dm-core/src/components/Pickers/Datepicker/Datepicker.tsx
- Uses `react portal` along with EDS's Popover to make sure popovers are always on top and behave nicely with scroll and parent components
closes #1263
> fix: popovers always on top

- packages/dm-core/src/components/Table/TableRow/TableRow.tsx
> fix: table expand bug

- packages/dm-core-plugins/src/list/ListPlugin.tsx
List had an issue where it scrolled horisontally it should not. 
Fixed in this PR.
> fix: list scroll when it should not

- packages/dm-core/src/components/Table/Table.tsx
So there was an issue on table where horisontal scroll was always on. 
This PR fixes this.
> fix: table-horitontal-scroll

- packages/dm-core-plugins/blueprints/stack/StackPluginConfig.json
- packages/dm-core-plugins/blueprints/stack/package.json
- packages/dm-core-plugins/src/index.tsx
- packages/dm-core-plugins/src/stack/StackPlugin.tsx
- packages/dm-core-plugins/src/stack/types.ts
- packages/dm-core/src/components/common/Stack/types.ts
- packages/dm-core/src/types.ts
Add StackPlugin to dm-core-plugins. Allows user to stack views on top or next to each other.
In items array, just pass viewConfig objects
Example of config:
```json
{
"name": "Dashboard",
"type": "CORE:UiRecipe",
"description": "ESS Plot",
"plugin": "@development-framework/dm-core-plugins/stack",
"config": {
"type": "PLUGINS:dm-core-plugins/stack/StackPluginConfig",
"items": [
{
"type": "CORE:ReferenceViewConfig",
"scope": "sce",
"recipe": "Date"
},
{
"type": "CORE:ReferenceViewConfig",
"scope": "job",
"recipe": "Fetch_Signals_OmniaTS"
},
{
"type": "CORE:ReferenceViewConfig",
"scope": "sce.signals",
"recipe": "List"
}
]
}
},
```
Open to discussing naming. "MultiView" to me seems like you can switch between multiple views of the same content. "Flexbox" is more css language. If we describe …
> feat: stack plugin

- e2e/tests/plugin-form-Media_viewer.spec.ts
- packages/dm-core-plugins/blueprints/media_viewer/MediaViewerConfig.json
- packages/dm-core/src/components/MediaContent/MediaContent.tsx
- packages/dm-core/src/components/MediaContent/types.ts
- New config: showDescription
- Show info-popover when showMeta OR showDescription is enabled
- Use filename as title if label is not provided 
- Hide description label if description is not provided
Want to actually hide meta
#1223
> fix: hide meta when disabled

- e2e/tests/plugin-table-car_list.spec.ts
Changed the order of a few asserts.
Test was flaky due to reloading happening before deleting is complete. Try to fix by using another assert to verify frontend before reloading.
Closes #1305
> fix: flaky table test

- packages/dm-core-plugins/blueprints/common/Meta.json
- packages/dm-core-plugins/blueprints/publish/PublishConfig.json
- packages/dm-core-plugins/blueprints/publish/package.json
- packages/dm-core-plugins/src/index.tsx
- packages/dm-core-plugins/src/meta/MetaPlugin.tsx
- packages/dm-core-plugins/src/publish/PublishPlugin.tsx
- packages/dm-core/src/components/CopyLinkDialog.tsx
Adds plugins for "Publish" and "Meta".
They are both wrappers, that just show a "publish button", and "meta info" before the main entity's plugin.
Closes #1148
> add meta and publish plugins

- packages/dm-core-plugins/src/data-grid/DataGridPlugin.tsx
- packages/dm-core-plugins/src/form/templates/ObjectModelContainedTemplate.tsx
When DataGridPlugin is a part of form/onChange function is passed to plugin, call onChange function instead of save
Form overwrites changes in DataGradPlugin if it's nested more than one time.
#1294
> fix: call form onChange instead of save in DataGridPlugin if passed

- .github/workflows/integration-tests.yaml
- e2e/tests/plugin-form-model_uncontained-complex_attribute.spec.ts
- e2e/tests/plugin-list-task_list.spec.ts
- example/.env.test
- example/docker-compose.yaml
- example/heat-cache.sh
Depends on https://github.com/equinor/data-modelling-storage-service/pull/791
- Run dmss in "prod"-mode for better performance
- Warm cache before running tests
flaky tests. Seems to be caused by performance issues
should help on #1307
> test: run integration tests with 4 workers

- example/docker-compose.yaml
> chore: bump mongo from 3.4 to 3.6

- example/app/data/DemoDataSource/plugins/list/task_list/blueprints/TaskList.blueprint.json
- example/app/data/DemoDataSource/plugins/list/task_list/taskList.entity.json
- example/app/data/DemoDataSource/plugins/table/car_list/blueprints/CarList.blueprint.json
- example/app/data/DemoDataSource/plugins/table/car_list/carList.entity.json
- packages/dm-core-plugins/src/list/ListPlugin.tsx
- packages/dm-core/src/components/Table/TableRow/TableRow.tsx
- packages/dm-core/src/hooks/useList/types.ts
- packages/dm-core/src/hooks/useList/useList.test.tsx
- packages/dm-core/src/hooks/useList/useList.tsx
- packages/dm-core/src/hooks/useList/utils.ts
- packages/dm-core/src/types.ts
- Items in lists (useList hook), now has an `idReference`. 
- Will be set to `_id=...` if "ensureUID", else use index
depends on:
- https://github.com/equinor/data-modelling-storage-service/pull/807
closes #1308
> feat: don't use index for address of item when 'ensureUID'

- e2e/tests/plugin-form-relative_reference.spec.ts
- example/app/data/DemoDataSource/plugins/publish/Archive.blueprint.json
- example/app/data/DemoDataSource/plugins/publish/PublishWrapper.blueprint.json
- example/app/data/DemoDataSource/plugins/publish/Report.blueprint.json
- example/app/data/DemoDataSource/plugins/publish/archive.entity.json
- example/app/data/DemoDataSource/plugins/publish/report.entity.json
- example/app/data/DemoDataSource/recipes/meta.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/publish/publishWrapper.recipe.json
- packages/dm-core-plugins/blueprints/publish/PublishConfig.json
- packages/dm-core-plugins/src/list/ListPlugin.tsx
- packages/dm-core-plugins/src/meta/MetaPlugin.tsx
- packages/dm-core-plugins/src/publish/PublishPlugin.tsx
- packages/dm-core/src/components/CopyLinkDialog.tsx
- packages/dm-core/src/components/Pickers/EntityPickerDialog.tsx
- packages/dm-core/src/hooks/useRecipe.tsx
- packages/dm-core/src/types.ts
- packages/dm-core/src/utils/truncatePathString.ts
- Added "copy&link" mode to "CopyLinkDialog"
- Fixed a bug in "useRecipe", where error where not reset when changing type
- Changed "truncatePathString" to truncate start of path instead of end
- Meta plugin can now show meta for any type, not just the "Meta" type
- Updated "PublishPlugin" to support "copy&link"
depends on:
- https://github.com/equinor/data-modelling-storage-service/pull/807
- https://github.com/equinor/data-modelling-storage-service/pull/808
closes #1330
> feat(publish): copy and link mode

- packages/dm-core-plugins/src/job/JobControl.tsx
- packages/dm-core/src/components/RefreshButton.tsx
Added testid to refresh button and jobstatus.
There were no suitable element to use with e2e-tests.
> fix: added testid to refresh button and jobStatus

- packages/dm-core-plugins/src/data-grid/DataGridPagination/DataGridPagination.tsx
> fix(datagrid): pagination should be high enough for numbers to fit

- packages/dm-core-plugins/src/data-grid/DataGrid.tsx
- packages/dm-core-plugins/src/data-grid/DataGridActions/DataGridActions.tsx
- packages/dm-core-plugins/src/data-grid/DataGridPlugin.tsx
- packages/dm-core-plugins/src/data-grid/styles.ts
- packages/dm-core/src/hooks/useJob.tsx
1. added clear button, and clearing functionality
2. fixed a datagrid bug where one could not submit empty datagrid
3. added tooltips to the small buttons. 
4. made empty datagrid be full width 
5. made action row have border on the left side
> fix: make datagrid clear button 

- packages/dm-core/src/components/Dialog.tsx
Not sure why, but the height of the Dialog got set to "0" on safari with "height: 100%".
Seems to work fine without it. 
closes #1331
> fix: Dialog got height 0 on webkit(safari)

- packages/dm-core-plugins/src/data-grid/DataGridActions/DataGridActions.tsx
- packages/dm-core-plugins/src/data-grid/DataGridPlugin.tsx
Only show clear button when rows are editable
> fix(data-grid): disable clear button when rows are not editable

- packages/dm-core-plugins/src/job/JobControl/JobControl.tsx
- packages/dm-core-plugins/src/job/common.tsx
- packages/dm-core/src/styles/main.css
Fixes some problems that were introduced in the job ui plugin feature. 
Progress bar now has padding and spans full width of the container. 
Not status and chip flows into each other. 
Also removed header, as it made the plugin less reusable. 
Fixes too much padding in the table row. 
Fixes this problem:
> fix: ui job control 

- packages/dm-core-plugins/src/view_selector/SidebarPlugin.tsx
Add missing wrapper around content in SidebarPlugin
Not using Content (TabsContent) in Sidebar anymore, but a wrapper is still necessary to make the layout work
> fix: add missing wrapper to sidebar content

- packages/dm-core-plugins/src/common/Stack/Stack.tsx
- packages/dm-core-plugins/src/common/Stack/types.ts
Removed use of React defaultProps, switch to merging configs
React defaultProps is being deprecated and it's causing warnings in the developer console
> refactor: remove deprecated react defaultProps

- example/app/data/DemoDataSource/recipes/plugins/job/jobContainer.recipe.json
- example/app/data/DemoDataSource/recipes/recurringJob.recipe.json
- packages/dm-core-plugins/blueprints/job/ControlConfig.json
- packages/dm-core-plugins/blueprints/job/CreateConfig.json
- packages/dm-core-plugins/src/job/JobControl/JobControl.tsx
- packages/dm-core-plugins/src/job/JobCreate.tsx
- packages/dm-core-plugins/src/job/common.tsx
Adds a optional "title" to jobPluginConfig and UI
Be able to describe what the "play button" does
closes #1418
> feat(job): configurable title

- packages/dm-core/src/ApplicationContext.tsx
- packages/dm-core/src/domain/Tree.ts
- Blueprint fetches in Tree did not use "context", resulting in double the amount of blueprint calls
> fix: include application context in Tree

- packages/dm-core-plugins/docs/DataGridPlugin/Examples/1D_Primitive_Array.json
- packages/dm-core-plugins/docs/DataGridPlugin/Examples/2D_Primitive_Array.json
- packages/dm-core-plugins/docs/DataGridPlugin/Examples/Multiple_Primitive_Arrays.json
- packages/dm-core-plugins/docs/FormPlugin/Examples/Basic.json
- packages/dm-core-plugins/docs/FormPlugin/Examples/Nested.json
- packages/dm-core-plugins/docs/FormPlugin/Examples/WidgetExample.json
- packages/dm-core-plugins/docs/ListPlugin/Examples/Basic.json
- packages/dm-core-plugins/docs/MediaViewerPlugin/Examples/Basic.json
- packages/dm-core-plugins/docs/MetaPlugin/Examples/Basic.json
- packages/dm-core-plugins/docs/ResponsiveGridPlugin/Examples/Basic.json
- packages/dm-core-plugins/docs/SidebarPlugin/Examples/Basic.json
- packages/dm-core-plugins/docs/StackPlugin/Examples/Basic.json
- packages/dm-core-plugins/docs/TablePlugin/Examples/Basic.json
- packages/dm-core-plugins/docs/TablePlugin/Examples/EditTable.json
- packages/dm-core-plugins/docs/TablePlugin/Examples/Nested.json
- packages/dm-core-plugins/docs/TabsPlugin/Examples/Basic.json
Add blueprintPaths to example recipes
Missing paths should be included
> fix: add blueprint paths to recipe examples

- packages/dm-core-plugins/package.json
- packages/dm-core/package.json
Move dnd packages from dm-core to dm-core-plugins
Sortable was moved to plugins from core, but packages were left behind
> fix: move dnd packages to correct project

- e2e/tests/plugin-explorer.spec.ts
- e2e/tests/plugin-list-task_list.spec.ts
- e2e/tests/plugin-view_selector-car_garage.spec.ts
- packages/dm-core-plugins/src/view_selector/Sidebar.tsx
Various integration test fixes
Pipeline fails
> fix: integration tests

- packages/dm-core-plugins/blueprints/stack/StackPluginConfig.json
- packages/dm-core-plugins/src/stack/StackPlugin.tsx
- packages/dm-core-plugins/src/stack/types.ts
- feat: add itemMaxWidths attribute to set maxWidths for child views of StackPlugin
If stack child has maxWidth, the parent wrapper should follow that width, but there doesn't seem to be a way around using full width in EntityView so it will always span full width and there's no way of knowing the maxWidth of child elements either. Best solution seems to be giving opportunity to set maxWidths of children in the actual StackPlugin config.
#1466
> feat: add itemMaxWidths attribute

- .github/workflows/codeql.yml
- .github/workflows/deploy-to-radix.yaml
- .github/workflows/integration-tests.yaml
- .github/workflows/on-main-push.yaml
- .github/workflows/publish-integration-tests-report.yaml
- .github/workflows/remove-integration-tests-report.yaml
- .github/workflows/reset-production.yaml
- .github/workflows/tests.yaml
Update action versions to v4
Pipeline is failing/skipping jobs with deprecated actions
> chore: update action versions

- packages/dm-core-plugins/src/view_selector/Sidebar.tsx
- fix: use default sidebar toggle
Our workaround of using a custom toggle so that we can collapse sidebar on window resize doesn't  work anymore as controlled sidebar in EDS doesn't seem to support controlled sidebar component. We can consider creating an issue in EDS, but for now we should at least be able to collapse using the button.
#1479
> fix: use default eds sidebar toggle

- packages/dm-core-plugins/src/table/Table/TableRow/TableRow.tsx
- fix: support integers in table edit
Integers not parsed as numbers ini table edit
#1474
> fix: parse integers as numbers on edit cell

- example/app/data/DemoDataSource/recipes/plugins/form/hyperlinks/LinkForm.recipe.json
- packages/dm-core-plugins/blueprints/form/widgets/HyperlinkWidgetConfig.json
- packages/dm-core-plugins/src/form/widgets/HyperlinkWidget.tsx
- Expands config for HyperLinkWidget
- add attribute target (follows html syntax)
- add attribute download
- add attribute customDownloadFilename (same as download, but with custom file name. HTML attribute accepts both bool and string, but we don't support that)
- General refactoring of HyperlinkWidget code
- By request
#1484
> feat: expanded config for hyperlinkwidget
