- packages/dmt-core/package.json
changelog: 
option to specify dmss url
> chore: deploy new dm-core package

- .github/workflows/on-main-push.yaml
- packages/dmt-core/package.json
fix build error with dm core package.
installing the package with yarn/npm is now working with the latest version: 1.0.12
bug with build
closes #9
> fix: dm core build error

- .github/workflows/on-main-push.yaml
- .github/workflows/tests.yaml
- packages/tabs/jest.config.js
- packages/tabs/package.json
- packages/tabs/src/TabsContainer.tsx
- packages/tabs/src/TabsContext.tsx
- packages/tabs/src/index.tsx
- packages/tabs/tsconfig.json
add tabs package.
The code inside the tabs packge is copied directly from dmt repo
dm-app-analysis-portal requires tabs package for viewing analyses
> feat: add tabs  package

- packages/blueprint/package.json
- packages/blueprint/src/EditBlueprint.tsx
- packages/blueprint/src/index.tsx
- packages/default-pdf/package.json
- packages/default-pdf/src/index.tsx
- packages/default-preview/package.json
- packages/default-preview/src/index.tsx
- packages/dm-core/package.json
- packages/dm-core/src/components/UiPluginSelector.tsx
- packages/dm-core/src/context/UiPluginContext.tsx
- packages/dm-core/src/types.ts
- packages/job/package.json
- packages/job/src/JobInputEdit.tsx
- packages/job/src/index.tsx
- packages/mermaid/package.json
- packages/mermaid/src/index.tsx
- packages/tabs/package.json
- packages/tabs/src/TabsContainer.tsx
- packages/tabs/src/index.tsx
- packages/yaml-view/package.json
- packages/yaml-view/src/index.tsx
add type
add type
related to https://github.com/equinor/create-dm-app/issues/23
closes #21
> fix: add type for exported plugins from applications

- packages/blueprint/package.json
- packages/blueprint/src/EditBlueprint.tsx
- packages/blueprint/src/index.tsx
- packages/default-pdf/src/index.tsx
- packages/default-preview/src/index.tsx
- packages/dm-core/package.json
- packages/dm-core/src/components/NewEntityButton.tsx
- packages/dm-core/src/components/UiPluginSelector.tsx
- packages/dm-core/src/components/UploadFileButton.tsx
- packages/dm-core/src/context/FileSystemTreeContext.tsx
- packages/dm-core/src/context/UiPluginContext.tsx
- packages/dm-core/src/domain/Tree.tsx
- packages/dm-core/src/hooks/useDataSources.tsx
- packages/dm-core/src/hooks/useDocument.test.tsx
- packages/dm-core/src/hooks/useDocument.tsx
- packages/dm-core/src/hooks/useJob.tsx
- packages/dm-core/src/services/api/configs/gen/api/default-api.ts
- packages/dm-core/src/services/api/configs/gen/api/document-api.ts
- packages/dm-core/src/services/api/configs/generate-dmss-api.sh
- packages/dm-core/src/utils/test-utils-dm-core.tsx
- packages/job/src/JobControl.tsx
- packages/job/src/JobInputEdit.tsx
- packages/job/src/index.tsx
- packages/mermaid/src/index.tsx
- packages/tabs/src/TabsContainer.tsx
- packages/tabs/src/index.tsx
- packages/yaml-view/src/index.tsx
- Update some functions to reflect the  DMSS endpoints that has changed
- Reverts some changes merged into main after https://github.com/equinor/dm-core-packages/commit/5f3b9bc4048c56c03f0b8c208be70e4e13a9fdcb as the core package was never published, and so all bumping refering to this unpublished packaged failed (@KristianKjerstad 
- DMSS api changed
closes #23
> fix(core): update on changed DMSS api

- packages/dm-core/package.json
- packages/dm-core/src/types.ts
NB! wait for https://github.com/equinor/dm-core-packages/pull/29 before merge to upload correct npm version
related to #27
> fix: update TPlugin type

- packages/dm-core/package.json
- packages/dm-core/src/Enums.ts
- Relates to https://github.com/equinor/data-modelling-storage-service/issues/276
> chore: rename protocol from sys => dmss

- README.md
* Change README.md content
* It show DMT instead of core packages repository content
> docs: change readme to reflect repository content

- packages/dm-core/package.json
- packages/dm-core/src/components/NewEntityButton.tsx
rename prop in NewEntityButton
code quality
part of #40
> refactor: rename setReference prop in NewEntityButton to onCreated

- example/src/App.js
- packages/dm-core/package.json
- packages/dm-core/src/domain/Tree.tsx
> fix: wrong blueprint key used in TreeNode

- example/app/data/DemoDataSource/DemoPackage/DummyBlueprint.json
- example/app/data/DemoDataSource/DemoPackage/dummy_entity.json
- example/app/data/DemoDataSource/DemoPackage/named_entity.json
- example/src/App.js
add example of how to use NewEntityButton
> feat: add example of NewEntityButton

- example/src/test_components/Jobs.tsx
- packages/blueprint/package.json
- packages/blueprint/src/EditBlueprint.tsx
- packages/dm-core/package.json
- packages/dm-core/src/components/Pickers/JobHandlerPicker.tsx
udate hardcoded types used to be compatible with latest dmss version
bugs
> fix: update hardcoded types used

- packages/dm-core/package.json
- packages/dm-core/src/components/UploadFileButton.tsx
- packages/dm-core/src/types.ts
- Removes the concept of different plugin types in UiPluginContext
- Remove some unused types
Technical debt and code quality
closes #46
> chore: single plugin type

- packages/dm-core/package.json
* Release new version of dm-core
* Publish new version
> build: bump core package

- example/package.json
Add command for building all packages
example/readme.md asks me to build all packages, and that sounded boring. So I wrote a tiny script for it
> chore: Add command for building all packages

- packages/dm-core/package.json
- packages/dm-core/src/components/AccessControl/ACLOwnerPanel.tsx
- packages/dm-core/src/components/AccessControl/ACLUserRolesPanel.tsx
- packages/dm-core/src/components/NewEntityButton.tsx
- packages/dm-core/src/components/Pickers/BlueprintPicker.tsx
* Upgrade EDS
* Use same EDS as in dm-core-plugins
> refactor: remove typescript errors

- example/app/data/DemoDataSource/DemoPackage/entities/recipesAsSidebar.json
rename test entity
make it more obvious that we have a test entity that uses this "secret" plugin
none relates to #110
> refactor(example): rename recipeSidebar  entity

- packages/dm-core/package.json
* Bump dm core package
* Make useRecipe and ViewCreator component available to be used
> build: bump dm core

- packages/dm-core/package.json
> build: dm core packages

- packages/dm-core-plugins/package.json
> build: bump dm core plugins

- packages/dm-core-plugins/package.json
- packages/dm-core-plugins/src/explorer/ExplorerPlugin.tsx
* Update explorer to use the latest dm-core package
* Update to use EntityView for display content on the right side. EntityView will make sure that the entity is correctly displayed  (correct recipe is chosen)
> bump: update dm-core package

- packages/dm-core-plugins/package.json
- packages/dm-core-plugins/src/generic-list/Components.tsx
- packages/dm-core-plugins/src/generic-list/GenericListPlugin.tsx
- packages/dm-core-plugins/src/generic-list/GenericTablePlugin.tsx
- packages/dm-core-plugins/src/generic-list/utils.ts
- Adds "reorder" functionality
- Refactor "generic-list" and "generic-table" to share some similar components
(note: image is outdated. There is now some padding around the "save"-button)
basic functionality as described in #109 
part of #109
> feature(generic-list): reorder items in list

- example/app/data/DemoDataSource/plugins/header/exampleApp.json
> fix: wrong reference

- example/app/data/DemoDataSource/apps/package.json
- example/app/data/DemoDataSource/apps/using-remote-package/blueprints/RemoteExample.json
- example/app/data/DemoDataSource/apps/using-remote-package/remoteExample.json
- example/app/data/ExtraDataSource/remote-package/blueprints/RemoteBlueprint.json
- example/app/data/ExtraDataSource/remote-package/entities/remoteEntity.json
- example/app/data/ExtraDataSource/remote-package/package.json
- example/app/data_sources/ExtraDataSource.json
- example/src/index.js
* Add extra data source 
* Add an example of an app that uses blueprints from the new data source
> Add remote package example

- example/app/data/DemoDataSource/plugins/attribute-selector/blueprints/AttributeSelectorSidebarBlueprint.json
- example/app/data/DemoDataSource/plugins/attribute-selector/blueprints/AttributeSelectorTabsBlueprint.json
- example/app/data/DemoDataSource/plugins/form/blueprints/Nested.json
- example/app/data/DemoDataSource/plugins/form/blueprints/SingleField.json
- example/app/data/DemoDataSource/plugins/generic-list/blueprints/Order.json
- example/app/data/DemoDataSource/plugins/generic-list/blueprints/OrderItem.json
- example/app/data/DemoDataSource/plugins/generic-list/blueprints/Product.json
- example/app/data/DemoDataSource/plugins/grid/blueprints/Dashboard.json
- example/app/data/DemoDataSource/plugins/grid/blueprints/Nested.json
- example/app/data/DemoDataSource/plugins/grid/blueprints/Order.json
- example/app/data/DemoDataSource/plugins/grid/blueprints/OrderItem.json
- example/app/data/DemoDataSource/plugins/grid/blueprints/Product.json
- example/app/data/DemoDataSource/plugins/header/blueprints/ExampleApplication.json
- example/app/data/DemoDataSource/plugins/sidebar-ui-recipes/blueprints/DummyBlueprint.json
- example/docker-compose.yaml
* Add type to all blueprints so that they are valid
> refactor: add type to all blueprints

- packages/dm-core/src/domain/Tree.tsx
* Tree should use new id reference format
> Tree should use new id reference format

- example/src/App.tsx
> refactor: use ts in App.js

- example/app/data/DemoDataSource/recipes/plugins/grid/dashboard.json
- packages/dm-core/src/components/ViewCreator/utils.ts
* Support scope using [] syntax
This needs to be fixed better in the future, maybe we should move the logic to backend.
> fix: scope with index to item in array

- packages/dm-core-plugins/package.json
- packages/dm-core-plugins/src/generic-list/Components.tsx
- packages/dm-core-plugins/src/generic-list/GenericListPlugin.tsx
- Adds pagination to "generic-list"-plugin
closes #109
> feature(generic-list): support for pagination

- example/README.md
Remove unecessary info from the README and simplify the steps needed to get the app running.
> docs: update README.md

- .github/workflows/tests.yaml
- example/src/test_components/Jobs.tsx
- packages/dm-core-plugins/package.json
- packages/dm-core/package.json
- packages/dm-core/src/components/UploadFileButton.tsx
- packages/dm-core/src/domain/Tree.tsx
- packages/dm-core/src/services/api/configs/gen/api/default-api.ts
- packages/dm-core/src/services/api/configs/gen/api/document-api.ts
- packages/dm-core/src/services/api/configs/gen/api/export-api.ts
- packages/dm-core/src/services/api/configs/gen/api/lookup-table-api.ts
update generated dmss api and a few usages of the api
#220
> chore: update generated dmss api

- packages/dm-core-plugins/package.json
- packages/dm-core-plugins/src/explorer/components/context-menu/utils/contextMenuActions.ts
- packages/dm-core-plugins/src/generic-list/GenericListPlugin.tsx
- packages/dm-core-plugins/src/job/JobControl.tsx
- packages/dm-core/src/components/TreeView.tsx
- packages/dm-core/src/domain/Tree.tsx
Before, the call to "expand tree" was buggy and did not do things in correct order. This issue is now fixed
Also, update some API calls that were wrong
closes #222
> fix: loading bug in tree

- .gitignore
- e2e/.gitignore
- e2e/package.json
- e2e/playwright.config.ts
- e2e/tests/plugin-form-NestedExample.spec.ts
- e2e/tests/plugin-form-formExample.spec.ts
- e2e/tests/signalApp.spec.ts
- example/package.json
- packages/dm-core-plugins/package.json
- packages/dm-core/package.json
Add Playwright using node
Needed for using playwright with latest changes.
> feat: playwright node

- .github/workflows/on-delete.yaml
- .github/workflows/remove-integration-tests-report.yaml
* Input what branch is deleted to the `remove-integration-tests-reports.yaml` workflow
> ci: input deleted branch to workflow

- .github/workflows/publish-integration-tests-report.yaml
* For each success in main, add entry to README.md
> ci: add entry to main readme

- .github/workflows/remove-integration-tests-report.yaml
* Small change, use correct inputs variable name to workflow
> fix: use correct variables for inputs to reusable workflow

- packages/dm-core-plugins/package.json
- packages/dm-core-plugins/src/explorer/components/context-menu/ContextMenu.tsx
- packages/dm-core/package.json
- packages/dm-core/src/components/NewEntityButton.tsx
- packages/dm-core/src/components/UploadFileButton.tsx
- packages/dm-core/src/domain/Tree.tsx
Fix some bugs in the tree
- right click and add blueprint
plus some small cleanup / refactoring
https://github.com/equinor/dm-core-packages/issues/220
> fix: bugs with tree

- .pre-commit-config.yaml
- e2e/README.md
- e2e/tests/signalApp.spec.ts
- example/app/data/DemoDataSource/recipes/apps/signal_app/recipe_links/signalAppUI.json
- example/package.json
> chore: rename SideBar UI plugin to View study in signal app and add readme to run e2e tests

- example/app/data/DemoDataSource/plugins/attribute-selector/blueprints/AttributeSelectorTabs.json
- packages/dm-core-plugins/package.json
- packages/dm-core-plugins/src/form/fields/ObjectField.tsx
fix bug with adding and opening uncontained entity in a form.
The bug occurred because new format of the reference has been implemented in dmss
https://github.com/equinor/dm-core-packages/issues/220
> fix: form plugin bug

- example/README.md
> docs: update readme

- packages/dm-core-plugins/package.json
* Upgrade dm core packages to use the latest dm core package
> chore: bump dm core packages

- example/app/data/DemoDataSource/recipes/plugins/form/formBlueprint.json
- packages/dm-core-plugins/src/form/fields/ObjectField.test.tsx
- packages/dm-core-plugins/src/form/fields/ObjectField.tsx
Refactor the form order function and add order test
> refactor: form order

- packages/dm-core/package.json
Dump dm-core to 1.0.61.
Builds to main are failing.
> chore: bump dm-core

- packages/dm-core-plugins/blueprints/form/fields/Field.json
- packages/dm-core-plugins/src/form/Form.test.tsx
- packages/dm-core-plugins/src/form/FormPlugin.tsx
- packages/dm-core-plugins/src/form/fields/ObjectField.test.tsx
- packages/dm-core-plugins/src/form/fields/ObjectField.tsx
- packages/dm-core-plugins/src/form/types.tsx
Creates a ts type for Form Config. Also fixes a bug in the blueprint
Refs #276
> refactor: create type for form config

- packages/dm-core/src/components/ViewCreator/utils.ts
- packages/dm-core/src/domain/Tree.tsx
- packages/dm-core/src/domain/types.ts
The typing seems a bit outdated. Now that it's up to date, we can use it more
> refactor: update ts types for blueprint and attr

- packages/dm-core/src/hooks/useBlueprint.tsx
- packages/dm-core/src/types.ts
> refactor: add correct types to useBlueprint

- .github/workflows/create-release-pr.yaml
* Forgot to remove default branch
> fix: change default branch to main

- packages/dm-core-plugins/blueprints/form/fields/ArrayField.json
- packages/dm-core-plugins/blueprints/form/fields/Field.json
- packages/dm-core-plugins/blueprints/form/fields/ObjectField.json
- packages/dm-core-plugins/blueprints/form/fields/StringField.json
- packages/dm-core-plugins/src/form/Form.test.tsx
- packages/dm-core-plugins/src/form/FormPlugin.tsx
- packages/dm-core-plugins/src/form/fields/AttributeField.tsx
- packages/dm-core-plugins/src/form/fields/ObjectField.tsx
- packages/dm-core-plugins/src/form/types.tsx
- packages/dm-core/src/hooks/useBlueprint.tsx
Add typing to ObjectField. Also fixes a bug in the blueprint and ts types for fields
More typing makes the code more readable == easier to refactor
Refs #276
> refactor: add types objectfield

- .pre-commit-config.yaml
Added pre-commit hooks to avoid commits to main and bad commit messages
> chore: add pre commit checks

- packages/dm-core/src/domain/Tree.tsx
fix bug with opening lists in the tree. Example: orders inside DashboardExample
#220
> fix: bug with opening lists in tree

- release-please-config.json
release-as locks the release please version to 1.1.0 permanently
> chore: unlock release please version

- example/README.md
Simply documenting naming conventions that we agree to use in the example app
#270
> Docs/ Documenting Naming Convention of Folders in the Example App

- .github/workflows/remove-integration-tests-report.yaml
The delete path was incorrect
Because the workflow keeps failing
> ci: fix bug in delete report workflow

- packages/dm-core-plugins/src/form/fields/ObjectField.tsx
Makes UncontainedAttribute cleaner
Refs #276
> refactor: move logic into AddUncontained

- packages/dm-core-plugins/src/form/fields/ObjectField.test.tsx
- packages/dm-core/src/hooks/useDocument.test.tsx
The import caused the following warning "It looks like you're using the wrong act() around your test interactions". That and the debug caused a lot of noise in the jest output
> test: remove noise from jest output

- example/README.md
apt-get **upgrade** -> apt-get **update** 
apt-get upgrade was duplicated in docs.
> docs: error in docs, should be update not upgrade

- example/job_handlers/signal-app-azure-container-job/calculate_signal.py
- example/job_handlers/signal-app-azure-container-job/publish-image.sh
- example/src/plugins/job-ui-single/pages/JobPlugin.tsx
> fix: build calculate signal container

- example/app/data/DemoDataSource/plugins/list/task_list/blueprints/Task.blueprint.json
- example/app/data/DemoDataSource/plugins/list/task_list/blueprints/TaskList.blueprint.json
- example/app/data/DemoDataSource/plugins/list/task_list/taskList.entity.json
- example/app/data/DemoDataSource/recipes/plugins/list/task_list/task.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/list/task_list/taskList.recipe.json
Added a new example case for list plugin.
For demonstration and testing purposes.
#369
> feat: list example plugin - tasklist

- packages/dm-core/src/components/NewEntityButton.tsx
- packages/dm-core/src/components/Pickers/EntityPickerButton.tsx
- packages/dm-core/src/components/TreeView.tsx
add functionality to pick attribute of an entity inside the entity picker button.
Before, it was only possible to pick an entity.
closes #361
> feat: add option to select attribute in entity picker

- e2e/tests/plugin-list-task_list.spec.ts
Added Playwright test for tasklist example plugin.
Bugs related to #153 and #258 is forcing us to temporary do some workarounds and comment some assertions out. These are marked in the spec-file.
> test: tasklist example

- packages/dm-core-plugins/src/form/Form.tsx
- packages/dm-core-plugins/src/form/fields/ObjectField.tsx
- packages/dm-core-plugins/src/form/types.tsx
Avoid using ObjectField directly from Form file
Allows for less recursiveness and stronger typing on ObjectField (will fix in new PR)
> refactor: use AttributeList directly

- packages/dm-core-plugins/src/form/fields/ArrayField.tsx
- packages/dm-core-plugins/src/form/fields/AttributeField.tsx
- packages/dm-core-plugins/src/form/fields/ObjectField.tsx
- packages/dm-core-plugins/src/form/types.tsx
Make the input types to ObjectField stronger, thus making the code easier to read
#276
> refactor: make stronger objectfield input types

- example/app/data/DemoDataSource/recipes/plugins/form/nested/carRentalCompany.recipe.json
- packages/dm-core-plugins/blueprints/form/fields/Field.json
- packages/dm-core-plugins/src/form/fields/ObjectField.tsx
- packages/dm-core-plugins/src/form/types.tsx
> refactor: rename isInline to showInline

- example/app/data/DemoDataSource/recipes/apps/EmployeeApp/employeeApp.recipe.json
- example/app/data/DemoDataSource/recipes/apps/signal_app/recipe_links/appDefault.recipe.json
- example/app/data/DemoDataSource/recipes/apps/signal_app/recipe_links/signals_simple/studyNC.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/grid/order.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/grid/orderItem.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/list/order_example/order.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/list/order_example/orderItem.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/list/task_list/task.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/list/task_list/taskList.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/table/car_list/carList.recipe.json
- packages/dm-core-plugins/blueprints/form/FormInput.json
- packages/dm-core-plugins/blueprints/grid/GridArea.json
- packages/dm-core-plugins/blueprints/grid/GridItem.json
- packages/dm-core-plugins/blueprints/grid/GridPluginConfig.json
- packages/dm-core-plugins/blueprints/grid/GridSize.json
- packages/dm-core-plugins/blueprints/header/HeaderPluginConfig.json
- packages/dm-core-plugins/blueprints/list/FunctionalityConfig.json
- packages/dm-core-plugins/blueprints/list/ListPluginConfig.json
- packages/dm-core-plugins/blueprints/table/TableFunctionalityConfig.json
- packages/dm-core-plugins/blueprints/table/TablePluginConfig.json
- packages/dm-core-plugins/blueprints/view_selector/RecipeSelectorConfig.json
- packages/dm-core-plugins/blueprints/view_selector/ViewSelectorConfig.json
- packages/dm-core-plugins/src/grid/types.ts
- packages/dm-core-plugins/src/list/ListPlugin.tsx
Fix various modeling errors that was found after validation in dm-cli was implemented.
note: seems like relative paths to blueprint is not working (https://github.com/equinor/dm-core-packages/issues/391)
> fix: modeling errors in documents

- .github/workflows/integration-tests.yaml
We recently had an issue where we updated dm-cli and the ci failed because it hadn't pulled the newest image for some time. This should fix it
also #397
> ci(integration-tests): run dc pull

- packages/dm-core-plugins/src/form/fields/ObjectField.tsx
Extracts functionality from ContainedAttribute into a new Inline component
The function had to many nested ifs and were hard to read
#276
> refactor(form): create inline component

- example/app/data/DemoDataSource/plugins/form/nested/blueprints/CarRentalCompany.blueprint.json
- example/app/data/DemoDataSource/recipes/plugins/form/nested/carRentalCompany.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/form/nested/customer.recipe.json
- packages/dm-core-plugins/src/form/fields/ObjectField.tsx
Adds examples
Uses showInline and uiRecipe for showing inline view. Open view will need further work
> refactor(form): simplify uncontained

- packages/dm-core-plugins/src/form/fields/ObjectField.tsx
Use watch() for getting form values for contained object attributes
getValues doesn't watch for changes and will not trigger re-render. Using it causes a lot of extra work. watch(), on the other hand, trigger re-renders
#276
> refactor(form): use watch to avoid double work

- e2e/README.md
Updated readme with more info and links to official Playwright documentation
> docs: update playwright readme

- example/app/data/DemoDataSource/plugins/view_selector/car_garage/blueprints/Car.blueprint.json
- example/app/data/DemoDataSource/plugins/view_selector/car_garage/blueprints/CarGarage.blueprint.json
- example/app/data/DemoDataSource/plugins/view_selector/car_garage/blueprints/Owner.blueprint.json
- example/app/data/DemoDataSource/plugins/view_selector/car_garage/blueprints/Tech.blueprint.json
- example/app/data/DemoDataSource/plugins/view_selector/car_garage/carGarage.entity.json
- example/app/data/DemoDataSource/recipes/plugins/view_selector/car_infosys/car.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/view_selector/car_infosys/carGarage.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/view_selector/car_infosys/owner.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/view_selector/car_infosys/technical.recipe.json
Added new example case for the view selector. The example uses both sidebar and tabs.
For demonstration and testing purposes.
> feat: view-selector example

- e2e/tests/plugin-view_selector-car_garage.spec.ts
Added Playwright test for the view-selector example.
> test: playwright test for view-selector example

- packages/dm-core/src/components/Pickers/EntityPickerButton.tsx
- packages/dm-core/src/domain/Tree.tsx
> fix: initFromFolder in tree not working

- example/docker-compose.yaml
> fix: stable dmss docker image version

- e2e/tests/plugin-form-Simple.spec.ts
- packages/dm-core-plugins/src/form/fields/AttributeField.tsx
- packages/dm-core-plugins/src/form/fields/NumberField.tsx
- packages/dm-core-plugins/src/form/types.tsx
Adds validation, does some rewrite and outcomments parts of a test
Missing validation for integers causes validation error in backend.
Closes #466
> fix(form): add validation for integers

- e2e/tests/plugin-form-UncontainedObject.spec.ts
- example/app/data/DemoDataSource/plugins/form/uncontained_object/blueprints/Company.blueprint.json
Playwright test for uncontained form example.
closes #444
> test: e2e uncontained form example

- example/docker-compose.yaml
> chore: update job-api image

- packages/dm-core-plugins/package.json
I don't think we're using this anywhere.
> chore: remove react-test-renderer

- packages/dm-core/src/domain/Tree.tsx
- packages/dm-core/src/types.ts
Creates the TPackage type and use in tree. Fix bugs that arise.
Typing helps us avoid bugs
> refactor: create TPackage and use in tree

- packages/dm-core/src/components/TreeView.tsx
Adds title to icons, thus removing the accessibility warning of missing text labels
Accessibility
ref #534
> fix(tree): add svg title

- e2e/playwright.config.ts
> test(e2e): disable retry in CI

- e2e/tests/plugin-header.spec.ts
- example/app/data/DemoDataSource/recipes/plugins/header/exampleApplication.recipe.json
- packages/dm-core-plugins/src/header/HeaderPlugin.tsx
Added Playwright test for header plugin
Added "title" to the menu button in HeaderPlugin to make it easier for Playwright.
Closes #545
> test: e2e header

- packages/dm-core/src/components/Pagination/Pagination.tsx
what the title says
its a bug
[#258](https://github.com/equinor/dm-core-packages/issues/258)
> Don't allow switching table pages if there are no more pages

- example/README.md
In the readme, added tip about enabling Rosetta in Docker to make the reset-app script run faster.
(Rest of the "changes" are just auto-formatting...)
> docs: added info about Rosetta i Docker

- packages/dm-core/src/domain/Tree.tsx
By changing input to an object, the arguments can be non-positional
Makes the code easier to read
ref #534
> refactor(tree): change input to TreeNode

- packages/dm-core/src/domain/Tree.tsx
Now you can pass in multiple roots to the tree, where they can point to different parts of the tree
ref #534
> feat(tree): make one init for everything

- .github/workflows/create-release-pr.yaml
> ci: use correct output name

- e2e/tests/plugin-list-task_list.spec.ts
Minor improvements to the E2E test for List plugin.
> refactor: minor improvements to list e2e-test

- example/reset-app.sh
* Force overwrite any data that already exists
fixes https://github.com/equinor/dm-cli/issues/143
> fix: add force flag

- example/.env.dev
- example/.env.prod
* Add URLs to the job API for dev and prod environments that are running in Radix
> chore: add job urls for radix

- example/docker-compose.yaml
> chore: bump dm job

- example/docker-compose.yaml
> chore: bump dmss version

- example/app/data/DemoDataSource/plugins/form/model_uncontained/blueprints/Person.blueprint.json
- example/app/data/DemoDataSource/plugins/form/model_uncontained/blueprints/Ship.blueprint.json
- example/app/data/DemoDataSource/plugins/form/model_uncontained/person.entity.json
- example/app/data/DemoDataSource/plugins/form/model_uncontained/ship.entity.json
* Add form example for model uncontained
> feat: model uncontained demo

- example/app/data/DemoDataSource/global/result.entity.json
- example/app/data/DemoDataSource/global/results/result.entity.json
- packages/dm-core-plugins/src/explorer/ExplorerPlugin.tsx
- packages/dm-core-plugins/src/form/fields/NumberField.tsx
- packages/dm-core-plugins/src/form/fields/ObjectField.tsx
- packages/dm-core-plugins/src/form/types.tsx
Adds another variant of the `ObjectFiled` that supports `storage: uncontained`.
closes #588
> feat: support storage uncontained in object field

- example/app/data/DemoDataSource/plugins/grid/car_grid/blueprints/Car.blueprint.json
- example/app/data/DemoDataSource/plugins/grid/car_grid/blueprints/CarList.blueprint.json
- example/app/data/DemoDataSource/plugins/grid/car_grid/blueprints/Nested.blueprint.json
- example/app/data/DemoDataSource/plugins/grid/car_grid/blueprints/RaceCenter.blueprint.json
- example/app/data/DemoDataSource/plugins/grid/car_grid/blueprints/Tyre.blueprint.json
- example/app/data/DemoDataSource/plugins/grid/car_grid/blueprints/TyreList.blueprint.json
- example/app/data/DemoDataSource/plugins/grid/car_grid/carList.entity.json
- example/app/data/DemoDataSource/plugins/grid/car_grid/raceCenter.entity.json
- example/app/data/DemoDataSource/plugins/grid/car_grid/tyreList.entity.json
- example/app/data/DemoDataSource/recipes/plugins/grid/car_grid/car.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/grid/car_grid/carList.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/grid/car_grid/nested.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/grid/car_grid/raceCenter.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/grid/car_grid/tyre.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/grid/car_grid/tyreList.recipe.json
Adding new example for Grid-plugin. The example will be expanded with more PRs later.
To be used for testing and demo purposes.
> test: grid example

- e2e/tests/plugin-list-task_list.spec.ts
- example/app/data/DemoDataSource/plugins/list/task_list/blueprints/UncontainedTaskList.blueprint.json
- example/app/data/DemoDataSource/plugins/list/task_list/task1.entity.json
- example/app/data/DemoDataSource/plugins/list/task_list/task2.entity.json
- example/app/data/DemoDataSource/plugins/list/task_list/taskList.entity.json
- example/app/data/DemoDataSource/plugins/list/task_list/uncontainedTaskList.entity.json
- packages/dm-core-plugins/src/explorer/components/dialogs/NewEntityDialog.tsx
- packages/dm-core-plugins/src/list/ListPlugin.tsx
- packages/dm-core/src/components/Pickers/EntityPickerDialog.tsx
- packages/dm-core/src/hooks/useDocument.tsx
Fairly big rewrite of "ListPlugin" so that it can handle lists of references
- The ListPlugin should handle all kind of lists
closes #624
> feat: check if elements in list are references

- packages/dm-core-plugins/src/yaml/YamlPlugin.tsx
- packages/dm-core/src/hooks/useDocument.tsx
Adds a field for controlling the depth of the reference resolving for the yaml plugin
#632
> feat(yaml): interactive depth

- packages/dm-core/src/hooks/useJob.tsx
Changes how the intervalID of the job pinger is stored. It now uses a ref instead of state, which doesn't trigger a re-render.
This change makes the pinger stop when the state is not `"running"`
#641
> fix: job pinger never stops

- example/app/data/DemoDataSource/recipes/apps/signal_app/recipe_links/signals_simple/case.recipe.json
- packages/dm-core-plugins/src/job/JobControlButton.tsx
- packages/dm-core-plugins/src/job/JobPlugin.tsx
- packages/dm-core/src/hooks/useDocument.tsx
- packages/dm-core/src/hooks/useJob.tsx
- Some refactoring and code cleanup
- JobControlButton now correctly show proper action that the user can take
- JobControlButton no longer remove jobs
-  'useDocument's update function is now async, with a "notify" parameter
- "useJob" now ties the status interval with the "jobHookId"
- Fixes multiple bugs with "useJob" and JobPugin
closes #647
> fix(jobPlugin): multiple issues with jobPlugin

- packages/dm-core-plugins/src/index.tsx
*  fix: export `WidgetProvider` to be able to provide custom widgets
> fix(form): export widget provider

- packages/dm-core-plugins/src/explorer/ExplorerPlugin.tsx
* Add padding to content in explorer plugin and increase the min width
> refactor(explorer): add padding around content

- packages/dm-core-plugins/src/form/widgets/SwitchWidget.tsx
- packages/dm-core-plugins/src/form/widgets/index.ts
* feat(form): add switch widget (similar to checkbox widget)
> feat(form): add switch widget

- e2e/tests/plugin-list-task_list.spec.ts
- packages/dm-core-plugins/src/list/ListPlugin.tsx
Tests are failing.
Trying to make them not do that.
> test: fix failing integration test

- e2e/tests/signalApp.spec.ts
- packages/dm-core-plugins/src/job/Colors.tsx
- packages/dm-core-plugins/src/job/CronJob.tsx
- packages/dm-core-plugins/src/job/DateRangePicker.tsx
- packages/dm-core-plugins/src/job/Input.tsx
- packages/dm-core-plugins/src/job/JobControlButton.tsx
- packages/dm-core-plugins/src/job/JobPlugin.tsx
- packages/dm-core/src/Enums.ts
- packages/dm-core/src/types.ts
Adds support for cron job in JobPlugin
Makes it possible to schedule the job for later
> feat: support for scheduling of cron jobs in JobPlugin

- packages/dm-core-plugins/src/list/ListPlugin.tsx
- packages/dm-core/jest.config.js
- packages/dm-core/jestSetup.js
- packages/dm-core/src/hooks/useList.test.tsx
- packages/dm-core/src/hooks/useList.tsx
- packages/dm-core/src/utils/test-utils-dm-core.tsx
* Use the `useList` hook inside `ListPlugin` to handle list operations
> refactor(list): use list hook

- .github/workflows/deploy-to-radix.yaml
- .github/workflows/integration-tests.yaml
- .github/workflows/tests.yaml
- Adds caching to some of the steps in the CI
- Increase CI speed, reduce cost, etc.
Linting and testing time is now 50% faster.
Which does not matter much since we are still waiting 7min on integration tests...
> build: cache node_modules

- packages/dm-core-plugins/src/job/CronJob.tsx
- packages/dm-core-plugins/src/job/JobPlugin.tsx
Fix typo: "Reoccurring" -> "Recurring"
> refactor: fix typo

- packages/dm-core-plugins/src/explorer/components/Sidebar.tsx
> fix: sidebar scrolling

- e2e/tests/plugin-view_selector-car_garage.spec.ts
Minor stabilisation for list test making sure the correct element is selected.
Incorrect element was sometimes selected causing the test to fail.
> fix(test): minor stabilisation for list test

- .gitignore
- packages/dm-core-plugins/src/form/components/AttributeList.tsx
> feat: hide type and meta by default

- e2e/tests/plugin-header-roles_header_example.spec.ts
- e2e/tests/plugin-view_selector-roles_school_example.spec.ts
Added Playwright tests for changing roles.
closes #590
> test(roles): integration test for roles

- e2e/tests/plugin-header-roles_header_example.spec.ts
- e2e/tests/plugin-view_selector-roles_school_example.spec.ts
Updating the roles test based on #708 
Test are failing if not updated.
> fix(roles): updating test using new save button

- example/app/data/DemoDataSource/recipes/apps/signal_app/recipe_links/signals_simple/case.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/grid/car_grid/raceCenter.recipe.json
- packages/dm-core-plugins/blueprints/grid/GridBorder.json
- packages/dm-core-plugins/blueprints/grid/GridItem.json
- packages/dm-core-plugins/blueprints/grid/GridPluginConfig.json
- packages/dm-core-plugins/src/explorer/ExplorerPlugin.tsx
- packages/dm-core-plugins/src/grid/GridElement.tsx
- packages/dm-core-plugins/src/grid/GridItems.tsx
- packages/dm-core-plugins/src/grid/GridPlugin.tsx
- packages/dm-core-plugins/src/grid/types.ts
* Show border (default off)
* Also possible to change the style of the border for items 
* Add title to grid items (default no title)
* Set gap size for columns and rows (default 16 px)
* Set size for columns and rows (default same size for all columns and rows)
> feat(grid): add border and title

- packages/dm-core/src/components/EntityView.tsx
- packages/dm-core/src/components/RefreshButton.tsx
- packages/dm-core/src/types.ts
> feat: refresh button

- example/docker-compose.yaml
> chore: bump dmss and dm-job versions

- e2e/tests/plugin-explorer.spec.ts
Basic Playwright test for Explorer plugin.
Closes #589
> test(explorer): playwright test for explorer

- packages/dm-core-plugins/src/list/Components.tsx
- packages/dm-core-plugins/src/list/ListPlugin.tsx
- packages/dm-core-plugins/src/table/TablePlugin.tsx
> feat: revert button in list

- example/app/data/DemoDataSource/recipes/apps/signal_app/recipe_links/containers/equallySpacedSignal.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/form/simple/simple.recipe.json
- example/docker-compose.yaml
- packages/dm-core/src/components/EntityView.tsx
> feat: default to false with show refresh button

- packages/dm-core-plugins/src/form/fields/NumberField.tsx
- packages/dm-core-plugins/src/form/fields/StringField.tsx
- packages/dm-core-plugins/src/form/types.tsx
- packages/dm-core-plugins/src/form/widgets/TextWidget.tsx
> feat(form): show if a value has changed

- example/package.json
> chore: upgrade vite

- example/docker-compose.yaml
- packages/dm-core/src/components/EntityView.tsx
Was negated but should not be!
> feat: hotfix on wrong negation

- example/docker-compose.yaml
> chore: update dmss version

- example/app/data/DemoDataSource/recipes/apps/signal_app/recipe_links/signals_simple/case.recipe.json
- example/docker-compose.yaml
- example/job_handlers/signal-app/__init__.py
- example/src/plugins/marmo-ui/containers/views/SignalPlot.tsx
- packages/dm-core-plugins/src/job/CronJob.tsx
- packages/dm-core-plugins/src/job/JobControlButton.tsx
- packages/dm-core-plugins/src/job/JobLogsDialog.tsx
- packages/dm-core-plugins/src/job/JobPlugin.tsx
- packages/dm-core-plugins/src/job/templateEntities.ts
- packages/dm-core/src/Enums.ts
- packages/dm-core/src/components/EntityView.tsx
- packages/dm-core/src/hooks/useJob.tsx
- packages/dm-core/src/types.ts
- Create recurring jobs when toggle on
- Some refactoring and cleanup in very big "JobPlugin"-file
closes https://github.com/equinor/dm-app-simpos/issues/52
> feat(job): create recurring job

- packages/dm-core/src/components/MediaContent.tsx
Added some roles and titles to make it easier for Playwright to locate the elements.
> fix: added roles and titles in MediaContent

- example/app/data/DemoDataSource/plugins/form/enums/blueprints/Enums.blueprint.json
- example/app/data/DemoDataSource/plugins/form/enums/blueprints/StringOptions.entity.json
- example/app/data/DemoDataSource/plugins/form/enums/enums.entity.json
- example/app/data/DemoDataSource/recipes/plugins/form/enums/enums.recipe.json
- packages/dm-core-plugins/blueprints/form/fields/Field.json
- packages/dm-core-plugins/blueprints/form/widgets/SelectWidgetConfig.json
- packages/dm-core-plugins/src/form/fields/ArrayField.tsx
- packages/dm-core-plugins/src/form/fields/AttributeField.tsx
- packages/dm-core-plugins/src/form/fields/StringField.tsx
- packages/dm-core-plugins/src/form/types.tsx
- packages/dm-core-plugins/src/form/widgets/SelectWidget.tsx
- packages/dm-core-plugins/src/form/widgets/index.ts
- packages/dm-core/src/types.ts
* Be able to use enums (`Enum` blueprint) in form
> feat: add enum support

- packages/dm-core-plugins/src/job/JobControlButton.tsx
- Turns the job controll button (run/stop/restart) into a simple button with only one icon
- Do stop and create in two steps
> fix: simple job control button

- .github/workflows/integration-tests.yaml
- e2e/playwright.config.ts
- e2e/tests/plugin-form-model_uncontained-complex_attribute.spec.ts
Changed from 1 to 4 workers. Run time is reduced approx 1 minute.
Tried with 6 workers also, but it kept failing. Need to monitor if 4 workers is stable enough.
> Perf: run playwright parallel

- e2e/tests/plugin-form-model_uncontained-complex_attribute.spec.ts
Test is still failing for some reason in the CI. Added another step to submit data.
> fix: model uncontained flaky in ci

- example/app/data/DemoDataSource/plugins/single_view/simple/blueprints/SingleContent.blueprint.json
- example/app/data/DemoDataSource/plugins/single_view/simple/blueprints/SingleView.blueprint.json
> fix: linting erros

- packages/dm-core-plugins/src/form/FormPlugin.tsx
- packages/dm-core-plugins/src/form/components/Form.tsx
- packages/dm-core-plugins/src/form/components/RemoveObjectButton.tsx
- packages/dm-core-plugins/src/form/types.tsx
- packages/dm-core/src/hooks/useDocument.tsx
- packages/dm-core/src/hooks/useRecipe.tsx
* Add support to the form plugin so that it only sends a payload to the API with attributes that should be updated (are visible)
> feat: partial update

- example/app/data/DemoDataSource/recipes/apps/ExampleApplication/ExampleApplication.recipe.json
* Change header options to explorer and yaml
> refactor: show yaml and explorer options

- .github/workflows/reset-production.yaml
> ci: promote dev to prod

- .gitignore
- example/tsconfig.json
- packages/dm-core-plugins/package.json
- packages/dm-core-plugins/src/index.tsx
- packages/dm-core/package.json
- packages/dm-core/src/index.tsx
- packages/dm-core/tsconfig.json
> refactor: fix tw build

- packages/dm-core-plugins/src/job/JobControlButton.tsx
- packages/dm-core-plugins/src/job/JobPlugin.tsx
> refactor: change job spinner icon, and remove refetch logs button

- e2e/tests/plugin-form-Simple.spec.ts
- example/src/App.tsx
- packages/dm-core-plugins/src/form/widgets/DateTimeWidget.tsx
- packages/dm-core-plugins/src/job/DateRangePicker.tsx
- packages/dm-core/src/components/Pickers/Datepicker/Datepicker.tsx
Replaces the old datepicker with the new datepicker.
Also makes some changes to how the props and interface of the datepicker, to make it fit more with the previous signature.
> refactor: use new datepicker

- packages/dm-core-plugins/src/list/ListPlugin.tsx
> chore: remove console log

- biome.json
- packages/dm-core-plugins/src/blueprint/BlueprintPlugin.tsx
- packages/dm-core-plugins/src/explorer/components/context-menu/getMenuItems.tsx
- packages/dm-core-plugins/src/file/FilePlugin.tsx
- packages/dm-core-plugins/src/file/UploadFileButton.tsx
- packages/dm-core-plugins/src/form/components/AttributeList.tsx
- packages/dm-core-plugins/src/form/components/Form.tsx
- packages/dm-core-plugins/src/form/fields/AttributeField.tsx
- packages/dm-core-plugins/src/form/fields/BinaryField.tsx
- packages/dm-core-plugins/src/form/fields/BooleanField.tsx
- packages/dm-core-plugins/src/form/test-utils.tsx
- packages/dm-core-plugins/src/form/widgets/SelectWidget.tsx
- packages/dm-core-plugins/src/header/components/UserInfoDialog.tsx
- packages/dm-core-plugins/src/job/CronJob.tsx
- packages/dm-core-plugins/src/job/JobPlugin.tsx
- packages/dm-core-plugins/src/view_selector/Content.tsx
- packages/dm-core-plugins/src/view_selector/Tabs.tsx
- packages/dm-core-plugins/src/view_selector/useViewSelector.tsx
- packages/dm-core/src/components/AccessControl/ACLUserRolesPanel.tsx
- packages/dm-core/src/components/Table/TableHead/TableHead.tsx
- packages/dm-core/src/components/TreeView.tsx
- packages/dm-core/src/components/UploadFileButton.tsx
- packages/dm-core/src/components/ViewCreator/utils.ts
- packages/dm-core/src/context/UiPluginContext.tsx
- packages/dm-core/src/domain/Tree.tsx
- packages/dm-core/src/hooks/useRecipe.tsx
- packages/dm-core/src/utils/addressUtilities.ts
- packages/dm-core/src/utils/objectUtilities.ts
- packages/dm-core/src/utils/stringUtilities.ts
Double equals are generally considered bad practice.
> refactor: use tripple equals instead of double

- example/app/data/DemoDataSource/recipes/plugins/grid/car_grid/tyre.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/grid/car_grid/tyreList.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/grid/example/order.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/grid/example/orderItem.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/list/order_example/order.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/list/order_example/orderItem.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/list/task_list/task.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/list/task_list/taskList.recipe.json
- packages/dm-core-plugins/blueprints/list/FunctionalityConfig.json
- packages/dm-core-plugins/blueprints/list/ListPluginConfig.json
- packages/dm-core-plugins/src/list/ListPlugin.tsx
- packages/dm-core-plugins/src/list/README.md
Support both open and expand at the same time with their separate view configs.
> feat: expand and open at the same time

- .release-please-manifest.json
- example/app/data/DemoDataSource/recipes/plugins/grid/car_grid/tyre.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/grid/car_grid/tyreList.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/grid/example/order.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/grid/example/orderItem.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/list/order_example/order.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/list/order_example/orderItem.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/list/task_list/task.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/list/task_list/taskList.recipe.json
- packages/dm-core-plugins/CHANGELOG.md
- packages/dm-core-plugins/blueprints/list/FunctionalityConfig.json
- packages/dm-core-plugins/blueprints/list/ListPluginConfig.json
- packages/dm-core-plugins/package.json
- packages/dm-core-plugins/src/blueprint/BlueprintAttribute.tsx
- packages/dm-core-plugins/src/blueprint/BlueprintAttributeList.tsx
- packages/dm-core-plugins/src/blueprint/BlueprintPlugin.tsx
- packages/dm-core-plugins/src/blueprint/DeleteSoftButton.tsx
- packages/dm-core-plugins/src/blueprint/Extends.tsx
- packages/dm-core-plugins/src/explorer/components/dialogs/NewEntityDialog.tsx
- packages/dm-core-plugins/src/list/ListPlugin.tsx
- packages/dm-core-plugins/src/list/README.md
- packages/dm-core/src/components/NewEntityButton.tsx
- packages/dm-core/src/components/Pickers/BlueprintPicker.tsx
- packages/dm-core/src/components/Pickers/Datepicker/Calendar.tsx
- packages/dm-core/src/components/Pickers/Datepicker/Datepicker.tsx
Modifies the old blueprint plugin. 
1. Better UI
2. Fixes bug of restoring that did not restore everything
> feat: better blueprint plugin

- packages/dm-core-plugins/src/blueprint/BlueprintAttribute.tsx
- packages/dm-core-plugins/src/blueprint/BlueprintAttributeList.tsx
- packages/dm-core-plugins/src/blueprint/BlueprintPlugin.tsx
Remoes a console.log 
also moves some code around
#871
> fix: remove console loggin and refactor

- packages/dm-core/src/components/Pickers/Datepicker/Calendar.tsx
- packages/dm-core/src/components/Pickers/Datepicker/Datepicker.tsx
> fix: fix some bugs

- e2e/tests/plugin-default_recipe.spec.ts
- e2e/tests/plugin-form-Nested.spec.ts
- e2e/tests/plugin-grid-car_grid.spec.ts
- e2e/tests/plugin-list-task_list.spec.ts
- example/app/data/DemoDataSource/recipes/plugins/grid/car_grid/tyre.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/grid/car_grid/tyreList.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/grid/example/order.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/grid/example/orderItem.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/list/order_example/order.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/list/order_example/orderItem.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/list/task_list/task.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/list/task_list/taskList.recipe.json
- packages/dm-core-plugins/blueprints/list/FunctionalityConfig.json
- packages/dm-core-plugins/blueprints/list/ListPluginConfig.json
- packages/dm-core-plugins/src/list/ListPlugin.tsx
- packages/dm-core-plugins/src/list/README.md
reverts some changes that were reverted by mistake.
> fix: revert changes

- packages/dm-core-plugins/src/explorer/components/context-menu/getMenuItems.tsx
- packages/dm-core/src/context/UiPluginContext.tsx
- Adds a "Copy address" entry in the context menu for Explorer
It's handy
> feat(Explorere): Copy entiity address

- e2e/tests/plugin-form-model_uncontained-complex_attribute.spec.ts
- packages/dm-core/src/components/MediaContent.tsx
- packages/dm-core/src/components/TreeView.tsx
- packages/dm-core/src/domain/Tree.tsx
Revert some changes that have were wrongly committed from the biome PR
> fix: hide binary again

- packages/dm-core/src/components/TreeView.tsx
> fix: actually hide binaries

- packages/dm-core-plugins/src/job/CrateFromRecipe.tsx
- packages/dm-core-plugins/src/job/JobControl.tsx
- packages/dm-core-plugins/src/job/common.tsx
- packages/dm-core/src/hooks/useJob.tsx
> chore: only show progress bar when job is running

- packages/dm-core-plugins/src/job/CrateFromRecipe.tsx
Better UI for the job progress, having it as int instead of 27.77777777%
> feat: job progress now is int

- e2e/tests/plugin-form-dimensional_scalar.spec.ts
Added Playwright test for dimensional scalar.
Closes #918
> test: playwright dimensional scalar

- e2e/tests/plugin-form-dimensional_scalar.spec.ts
Trying to make the test run more stable i CI.
> fix: dimensional scalar unstable test

- packages/dm-core-plugins/src/yaml/YamlPlugin.tsx
> fix: yaml overflow

- SECURITY.md
Added security.md as required in Equinor´s SCM policy.
> docs: security reporting policy

- packages/dm-core/src/components/Pickers/Datepicker/calendarUtils.ts
- fixes bug that sets day as month when selecting from previous month
> fix: selecting prev month date

- example/reset-app.sh
* chore: time how much time we are using on reset blueprints and entities
> chore: time reset app using cli

- packages/dm-core/src/components/Table/Table.tsx
- packages/dm-core/src/components/TemplateMenu.tsx
* fix: save added row to DMSS when adding a item in not edit mode
> fix: multiple templates not save when add

- packages/dm-core-plugins/src/form/fields/ArrayField.tsx
- packages/dm-core-plugins/src/form/templates/ObjectModelContainedTemplate.tsx
* fix: set the state as dirty on update so that save button is enabled
> fix: set dirty state after update

- packages/dm-core-plugins/src/job/CrateFromRecipe.tsx
> fix: do not show job status when it is unknown

- packages/dm-core-plugins/src/form/components/PrimitiveArray.tsx
- packages/dm-core-plugins/src/form/fields/AttributeField.tsx
- packages/dm-core-plugins/src/form/fields/NumberField.tsx
- packages/dm-core-plugins/src/form/fields/StringField.tsx
1. moved config for backgrounColor into the "config" where it belongs.
> refactor: move config into right place

- example/app/data/DemoDataSource/recipes/plugins/form/nested/carRentalCompany.recipe.json
- packages/dm-core-plugins/src/form/components/Form.tsx
- packages/dm-core-plugins/src/form/fields/StringField.test.tsx
1. Removed disabling of submit buttons after feedback. 
2. Re-Added tests that were removed because they did not make sense after disabled submit button.
> Fix: no disabled submit button

- example/app/data/DemoDataSource/recipes/apps/EmployeeApp/employee.recipe.json
- example/app/data/DemoDataSource/recipes/plugins/table/car_list/carList.recipe.json
- packages/dm-core-plugins/blueprints/list/ListPluginConfig.json
- packages/dm-core-plugins/blueprints/table/TablePluginConfig.json
- packages/dm-core-plugins/src/list/ListPlugin.tsx
- packages/dm-core/src/components/Table/TableRow/TableRow.tsx
- packages/dm-core/src/components/Table/types.ts
> fix: add indexLabel to list and table plugin

- packages/dm-core-plugins/src/form/widgets/DateTimeWidget.tsx
> fix(datepicker): Actually pass the variant from config to the daticker

- packages/dm-core-plugins/src/job/CrateFromRecipe.tsx
- packages/dm-core-plugins/src/job/CronJob.tsx
- packages/dm-core-plugins/src/job/JobLogsDialog.tsx
- packages/dm-core-plugins/src/job/LogBlock.tsx
- packages/dm-core-plugins/src/mediaViewer/MediaViewerPlugin.tsx
- packages/dm-core-plugins/src/view_selector/Sidebar.tsx
- packages/dm-core-plugins/src/yaml/YamlPlugin.tsx
- packages/dm-core/src/components/EntityView.tsx
- Toggling "job is recurring" does not hide the toggle component
- Advanced schedule view is hidden by default
- Setting advanced schedule hides "simple" input, and vice versa
- Make the log itself scroll able on overflow, not the whole modal hiding buttons and title
- When media is loading, don't show message "Not found", but "Loading..."
- Color background of selected menuItem (Sidebar)
- Center copy buttons in Yaml
> style: fix many minor style issues

- packages/dm-core-plugins/src/job/CrateFromRecipe.tsx
- packages/dm-core-plugins/src/job/JobControl.tsx
> fix: set recurring job as registered based on status from hook

- example/package.json
- packages/dm-core-plugins/package.json
- packages/dm-core/package.json
bumps tailwind to 3.4.0
version 3.4.0 has some cool features.
> chore: bump tailwind to 3.4.0

- example/app/data/DemoDataSource/recipes/plugins/mediaViewer/mediaViewer.recipe.json
- packages/dm-core-plugins/blueprints/media_viewer/MediaViewerConfig.json
- packages/dm-core-plugins/blueprints/media_viewer/package.json
- packages/dm-core-plugins/src/mediaViewer/MediaViewerPlugin.tsx
- packages/dm-core/src/components/MediaContent.tsx
Makes it possible to toggle the meta dropdown, and provide a caption & description for media objects.
closes #1029
> feat(media): Meta information config

- .pre-commit-config.yaml
- biome.json
Replaces the local hook with the official biome pre-commit hook.
> Use official biome pre-commit hook

- packages/dm-core/src/components/Pickers/EntityPickerDialog.tsx
> fix(EntityPicker): Only checkboxes clickable in 'multi-mode'

- e2e/tests/plugin-table-car_list.spec.ts
- example/app/data/DemoDataSource/plugins/table/car_list/carList.entity.json
Added test using table templates.
> test: added test for table templates

- e2e/tests/plugin-list-template.spec.ts
Test for adding list items using predefined templates.
> test: add list items using template

- .github/workflows/create-release-pr.yaml
- release-please-config.json
* Upgrade Release Please to version 4
> ci: upgrade release please to use version 4

- e2e/tests/plugin-form-relative_reference.spec.ts
- example/app/data/DemoDataSource/plugins/form/relative_reference/task.entity.json
Playwright test for relative references.
> test: e2e relative references

- packages/dm-core/src/components/MediaContent.tsx
> fix: rename to upload date

- example/app/data/DemoDataSource/recipes/plugins/form/nested/carRentalCompany.recipe.json
- packages/dm-core-plugins/src/form/templates/ArrayComplexTemplate.tsx
- packages/dm-core-plugins/src/form/templates/ArrayPrimitiveListTemplate.tsx
- packages/dm-core-plugins/src/form/templates/ObjectModelContainedTemplate.tsx
- packages/dm-core-plugins/src/form/templates/ObjectModelUncontainedTemplate.tsx
- packages/dm-core-plugins/src/form/templates/ObjectStorageUncontainedTemplate.tsx
- packages/dm-core-plugins/src/form/templates/shared/FormTemplate.tsx
Fixed a bug where hideOptional did not work for model contained
> fix: hide optional not working for contained

- packages/dm-core/src/components/MediaContent.tsx
> fix: wrapping in mediaView text box

- packages/dm-core-plugins/src/data-grid/DataGrid.tsx
- packages/dm-core-plugins/src/data-grid/DataGridActions/DataGridActions.tsx
- packages/dm-core-plugins/src/data-grid/DataGridPlugin.tsx
- packages/dm-core-plugins/src/data-grid/HeaderCell/HeaderCell.tsx
- packages/dm-core-plugins/src/data-grid/styles.ts
- packages/dm-core-plugins/src/data-grid/types.ts
- packages/dm-core-plugins/src/data-grid/utils.ts
Allows exporting data from datagrid.
- Copy data to clipboard
- Export as csv file
Want to export data from datagrid to use in programs like excel.
#998
> feat: export data as csv or copy

- example/app/data/DemoDataSource/recipes/plugins/form/nested/carRentalCompany.recipe.json
- packages/dm-core-plugins/blueprints/form/fields/ObjectField.json
- packages/dm-core-plugins/src/form/templates/ArrayComplexTemplate.tsx
- packages/dm-core-plugins/src/form/templates/ObjectModelContainedTemplate.tsx
- packages/dm-core-plugins/src/form/templates/ObjectModelUncontainedTemplate.tsx
- packages/dm-core-plugins/src/form/templates/ObjectStorageUncontainedTemplate.tsx
> refactor: readonly instead of hideDelete

- packages/dm-core-plugins/src/file/FilePlugin.tsx
- packages/dm-core-plugins/src/mediaViewer/MediaViewerPlugin.tsx
- packages/dm-core-plugins/src/pdf/PdfPlugin.tsx
> refactor: adjust depth levels

- packages/dm-core/src/components/LazyLoad.tsx
- packages/dm-core/src/components/Table/TableRow/TableRow.tsx
Table expansion was only in one cell, this fixes the issue.
> fix: table one cell bug

- example/src/index.tsx
- packages/dm-core-plugins/src/data-grid/DataGrid.tsx
- packages/dm-core-plugins/src/data-grid/DataGridPlugin.tsx
- packages/dm-core-plugins/src/data-grid/styles.ts
- packages/dm-core-plugins/src/explorer/ExplorerPlugin.tsx
- packages/dm-core-plugins/src/form/components/Form.tsx
- packages/dm-core-plugins/src/form/templates/shared/FormTemplate.tsx
- packages/dm-core-plugins/src/grid/GridElement.tsx
- packages/dm-core-plugins/src/grid/GridPlugin.tsx
- packages/dm-core-plugins/src/header/HeaderPlugin.tsx
- packages/dm-core-plugins/src/header/components/AboutDialog.tsx
- packages/dm-core-plugins/src/header/components/UserInfoDialog.tsx
- packages/dm-core-plugins/src/job/common.tsx
- packages/dm-core-plugins/src/list/ListPlugin.tsx
- packages/dm-core-plugins/src/view_selector/SidebarPlugin.tsx
- packages/dm-core-plugins/src/view_selector/TabsPlugin.tsx
- packages/dm-core-plugins/src/yaml/YamlPlugin.tsx
- packages/dm-core/src/components/Dialog.tsx
- packages/dm-core/src/components/EntityView.tsx
- packages/dm-core/src/components/LazyLoad.tsx
- packages/dm-core/src/components/MediaContent.tsx
- packages/dm-core/src/components/Table/Table.tsx
- packages/dm-core/src/components/ViewCreator/InlineRecipeView.tsx
remove fixed width on:
- explorer plugin
(scrollable horizontally and vertically)
Horizontal scroll was not possible with fixed width
> fix: explorer overflow

- e2e/tests/plugin-header-roles_header_example.spec.ts
- packages/dm-core-plugins/jest.config.js
- packages/dm-core-plugins/jestSetup.js
- packages/dm-core/src/components/Table/TableRow/TableRow.tsx
- packages/dm-core/src/context/DMSSContext.tsx
- Cache getBlueprint in frontend
part of #1173
> perf: cache getBlueprint calls

- packages/dm-core/src/components/CopyLinkDialog.tsx
> style: min width for copy dialog

- packages/dm-core-plugins/src/form/fields/BooleanField.tsx
- packages/dm-core-plugins/src/form/widgets/CheckboxWidget.tsx
> fix: required boolean field in form

- example/app/data/DemoDataSource/recipes/plugins/grid/example/dashboard.recipe.json
- example/src/index.tsx
- packages/dm-core-plugins/blueprints/grid/GridSize.json
- packages/dm-core-plugins/src/grid/GridPlugin.tsx
- packages/dm-core-plugins/src/grid/types.ts
- packages/dm-core-plugins/src/view_selector/TabsPlugin.tsx
- packages/dm-core/src/components/EntityView.tsx
- packages/dm-core/src/components/LazyLoad.tsx
- packages/dm-core/src/components/MediaContent.tsx
Add configuration to GridSize to set a optional fixed size for grid.
Gives possibility to give more space to each grid element if needed
https://github.com/equinor/dm-core-packages/assets/43639886/6cae060e-0ec6-41bc-9bd0-a314c5f2a61f
Closes #1213
> feat: configure fixed grid size

- packages/dm-core-plugins/blueprints/table/TableColumnConfig.json
- packages/dm-core/src/components/Pickers/Datepicker/calendarUtils.test.ts
- packages/dm-core/src/components/Pickers/Datepicker/calendarUtils.ts
- packages/dm-core/src/components/Table/TableRow/TableCell/TableCell.tsx
- packages/dm-core/src/components/Table/types.ts
- Added a "datetime" type for the table plugin
closes https://github.com/equinor/dm-app-simpos/issues/145
> feat(table): support for datetime dataTypes

- packages/dm-core/src/components/Pickers/Datepicker/Datepicker.tsx
- Use reacts "createPortal" to place the popover on "document.body" and set an absolute position based on parent.
popover was not visible if there wasn't enough space
closes #1208
> fix(datepicker): popover is now a portal on body. Always visible

- packages/dm-core/src/components/LazyLoad.tsx
> fix: content in table not using full width

- packages/dm-core/src/components/Pickers/Datepicker/Datepicker.tsx
https://jam.dev/c/f8e7f79b-b7fc-4eb9-a0d6-0ad02e08cdd4
> fix: datepicker does not open when edit as text

- packages/dm-core/src/components/Table/TableRow/TableCell/TableCell.tsx
> fix(table): fixed nb locale for table datetime

- packages/dm-core/src/components/EntityView.tsx
Fixes header not expanding and fetch job expanding too much
Closes #1258 #1257
> fix: make refresh button container full widh + height

- packages/dm-core-plugins/src/form/components/Form.tsx
- packages/dm-core-plugins/src/form/widgets/common/StyledInputFields.tsx
- packages/dm-core/src/components/Table/Table.tsx
- packages/dm-core/src/components/Table/TableRow/SkeletonRow.tsx
1. Fix a bug where no reset form buttons worked, made the form crash. Had to rewrite how we re-mounted the form after reset. 
2. Gave skeleton rows also keys.
> fix: form crashing bug

- .github/workflows/on-main-push.yaml
Release please bool instead of string
> fix: use bool instead of string

- packages/dm-core-plugins/src/list/ListPlugin.tsx
List plugin has scroll bar on pagination. 
This PR removes this.
> fix: no scroll bar on pagination in list

- packages/dm-core/src/components/Table/Table.tsx
Use list index instead of paginatedItems indx.
> fix(table): indexing problem

- packages/dm-core-plugins/src/job/CronJob.tsx
- packages/dm-core-plugins/src/job/DateRangePicker.tsx
- packages/dm-core-plugins/src/job/JobControl.tsx
- packages/dm-core-plugins/src/job/SimpleJobControlButtons.tsx
- packages/dm-core-plugins/src/job/common.tsx
- packages/dm-core/src/hooks/useJob.tsx
- Can no longer set time for recurring jobs "from" "to"
- Plugin no longer crashes if trying to start with invalid cron syntax
- Added text to inform  that times are in UTC
- Styling so that "Simple" and "Advanced" button don't shift around
bugs
closes #1303 
a few from #1252
> fix(job): a few bugs in scheduler ui

- packages/dm-core-plugins/src/table/TablePlugin.tsx
- packages/dm-core/src/components/Table/Table.tsx
- packages/dm-core/src/components/Table/types.ts
Allow user to revert changes in table (when in edit mode)
Wanted functionality
> feat: allow revert table changes in edit mode

- packages/dm-core-plugins/src/job/SimpleJobControlButtons.tsx
- packages/dm-core-plugins/src/list/ListPlugin.tsx
- packages/dm-core/src/components/LazyLoad.tsx
- packages/dm-core/src/components/Table/TableRow/TableRow.tsx
- packages/dm-core/src/styles/main.css
1. Tooltip on job runner
2. Fixed row overflow bug
> fix: ui bugs

- README.md
> chore: add compiliant badge

- .github/workflows/on-release.yaml
This test has been failing for a month now .. so comment this out. 
Must be fixed before it is here.
> fix: comment failing radix workflow

- packages/dm-core-plugins/src/data-grid/DataGridActions/DataGridActions.tsx
- packages/dm-core/src/hooks/useJob.tsx
1. Remove console.log that slipped through then merging
2. Added tooltip to settings button as well.
> fix: tooltip and remove console.log

- packages/dm-core-plugins/src/data-grid/DataGrid.tsx
- packages/dm-core-plugins/src/data-grid/DataGridActions/DataGridActions.tsx
- packages/dm-core-plugins/src/data-grid/DataGridPlugin.tsx
- packages/dm-core-plugins/src/data-grid/types.ts
> fix: remove dependency + call function so that it doesn't create loop

- packages/dm-core/src/components/Dropdown.tsx
Makes it so that the whole checkbox + label is clickable.
> fix: can't click name on dropdown

- packages/dm-core/src/components/Table/Table.tsx
Minor fix on eds button creating scroll 
Something in eds button has overflow that pushes parent height
> fix: edsbutton overflow minor fix

- packages/dm-core-plugins/src/job/common.tsx
> fix: job dialog misaligned when in flex

- packages/dm-core-plugins/src/yaml/YamlPlugin.tsx
- packages/dm-core/src/hooks/useDocument.tsx
- Implements a _simple_ "raw edit json mode" to the yaml-plugin 
Its very basic and limited. But i think it does the job, and avoids pulling in a 100MB editor NPM dependency
closes #1411
> feat(yaml): raw json edit

- example/Dockerfile
Update node version in example app build
Need to update after vite v6 update
> fix: update node version
